### ISSUE TITLE
Wrong location in Teslas mobile app with teslamate connected

### ISSUE THREAD

**Issue by fayelund** [adriankumpf/teslamate#1681] opened 2021-06-04 09:51 UTC
When I have teslamate connected to my Tesla account the location of the car in my Tesla mobile app gets wrong. The car shows up in correct prosition for about a second, then its normally some place in the middle of an ocean(north of russia or between Africa and India) or not updating at all.
Turning of my teslamate server makes the localisation behave correctly again.

**Comment by adriankumpf** [comment] 2021-06-04 10:01
Duplicate of https://github.com/adriankumpf/teslamate/discussions/1235

**Closed by adriankumpf** 2021-06-04 10:01 UTC
