### ISSUE TITLE
Can't browse web UI 

### ISSUE THREAD

**Issue by kstephens1** [adriankumpf/teslamate#3029] opened 2022-12-21 18:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Can't browse web UI http://192.168.1.86:4000/
Docker Logs show teslamate_teslamate_1 exited with code 134
This is running on a Raspberry Pi 4 Model B Rev 1.2

### Expected Behavior

Web UI should render into browser

### Steps To Reproduce

Install and launch docker images as per https://docs.teslamate.org/docs/installation/docker 

### Relevant log output

```shell
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | sleep: cannot read realtime clock: Operation not permitted
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_teslamate_1 exited with code 134
```

### Type of installation

Docker

### Version

latest docker image

**Comment by cwanja** [comment] 2022-12-21 18:31
See #2302. What OS are you running?

**Comment by kstephens1** [comment] 2022-12-21 18:35
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

NAME="Raspbian GNU/Linux"

VERSION_ID="10"

VERSION="10 (buster)"

**Comment by cwanja** [comment] 2022-12-21 18:38
You will need to upgrade to Bullseye. Or there's a comment with a potential library upgrade without upgrading the OS. There's links in that thread to upgrade guides and other issues as well.

**Comment by kstephens1** [comment] 2022-12-21 18:40
Thanks, I'll check it out.
*Keith Stephens*
Email: ***@***.***
Tel: +44 (0)7555 726575

**Comment by adriankumpf** [comment] 2023-01-13 11:11
Duplicate of #2302

**Closed by adriankumpf** 2023-01-13 11:11 UTC
