### ISSUE TITLE
Backup Script in Documentation not working

### ISSUE THREAD

**Issue by mailkluge** [adriankumpf/teslamate#2405] opened 2022-01-29 20:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to create a backup with the backup script shown in the documentation.

docker-compose exec -T database pg_dump -U teslamate teslamate > /backuplocation/teslamate.bck

This script creates always a teslamate.bck file with 0 Byte.

### Relevant log output

```shell
I added a "-d" to solve the issue.

docker-compose exec -T database pg_dump -U teslamate -d teslamate > /backuplocation/teslamate.bck

This script works well!
```

### Type of installation

Docker

### Version

v.1.25.2

**Comment by adriankumpf** [comment] 2022-01-29 22:29
Duplicate of https://github.com/adriankumpf/teslamate/issues/453

**Closed by adriankumpf** 2022-01-29 22:29 UTC
