### ISSUE TITLE
Grafana Charges reports incorrect start time resulting in wrong kWh added / used

### ISSUE THREAD

**Issue by fvanson** [adriankumpf/teslamate#1884] opened 2021-08-05 17:49 UTC
**Describe the bug:**

Charges overview in Grafana uses incorrect start time resulting in wrong kWh added / used. I have for my company Tesla both TeslaMate and TeslaFi running in order to have a back-up in case one system has issues, and TeslaFi correctly reports start time as well as kWh added / used.

**Expected behavior:**

Reporting of the real start time of charging in Grafana’s Charges overview, and using the real start time to calculate (the correct) kWh added / used during that session.

**How to reproduce it (as minimally and precisely as possible):**

In the example below, 'Grafana > TeslaMate > Charges' is showing a starting time of 2021-08-04 22:53:49 at 17% SoC.
When going into the 'Charge Details' of this charge, you will initially see the same starting time and starting SoC. But you can change the time range to an earlier one. In the example attached I changed start time to 2021-08-04 **22:00:00**. Then out of the TeslaMate database, the starting SoC was **8%** instead of 17%, and start time in the database is **22:10:42** instead of 22:53:49. So data and logging of data started earlier than reported in 'Charges' under Grafana.

**Steps to reproduce the behavior:**

See ‘How to reproduce it’ .

**Relevant entries from the logs**

See below relevant part of the TeslaMate log
…
teslamate2_1  | 2021-08-04 20:07:04.336 car_id=1 [info] Received stream data: :inactive
teslamate2_1  | 2021-08-04 20:07:05.507 [error] Vehicle Error: Vehicle is offline
teslamate2_1  | 2021-08-04 20:07:12.197 car_id=1 [info] Start / :offline
teslamate2_1  | 2021-08-04 20:07:12.206 car_id=1 [info] Disconnecting ...
teslamate2_1  | 2021-08-04 20:07:54.064 car_id=1 [info] Start / :online
teslamate2_1  | 2021-08-04 20:07:54.081 car_id=1 [info] Connecting ...
teslamate2_1  | 2021-08-04 20:07:54.084 car_id=1 [info] Driving / Start
teslamate2_1  | 2021-08-04 20:09:18.441 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (158.828 ms)
teslamate2_1  | 2021-08-04 20:09:18.917 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (474.122 ms)
teslamate2_1  | 2021-08-04 20:09:18.934 car_id=1 [info] Driving / Ended / 0 km – 1 min
teslamate2_1  | 2021-08-04 20:09:18.934 car_id=1 [info] Start / :online
teslamate2_1  | 2021-08-04 20:10:32.137 car_id=1 [info] Charging detected: -2 kW
teslamate2_1  | 2021-08-04 20:10:32.138 car_id=1 [info] Charging detected: -1 kW
teslamate2_1  | 2021-08-04 20:10:32.138 car_id=1 [info] Fetch already in progress ...
teslamate2_1  | 2021-08-04 20:10:33.192 car_id=1 [info] Charging detected: -3 kW
teslamate2_1  | 2021-08-04 20:10:33.192 car_id=1 [info] Fetch already in progress ...
teslamate2_1  | 2021-08-04 20:10:34.528 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (100.289 ms)
teslamate2_1  | 2021-08-04 20:10:34.554 car_id=1 [info] Charging / SOC: 8% / Thuis
teslamate2_1  | 2021-08-04 20:10:34.554 car_id=1 [info] Disconnecting ...
teslamate2_1  | 2021-08-04 20:11:53.395 [info] GET /
teslamate2_1  | 2021-08-04 20:11:53.403 [info] Sent 200 in 7ms
teslamate2_1  | 2021-08-04 20:11:54.784 [info] GET /
teslamate2_1  | 2021-08-04 20:11:54.793 [info] Sent 200 in 8ms
teslamate2_1  | 2021-08-04 20:24:50.700 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/221606540911/vehicle_data -> 408 (29874.367 ms)
teslamate2_1  | 2021-08-04 20:24:50.916 car_id=1 [warn] Discarded incomplete fetch result
teslamate2_1  | 2021-08-04 20:51:05.551 [info] GET /
teslamate2_1  | 2021-08-04 20:51:05.559 [info] Sent 200 in 8ms
teslamate2_1  | 2021-08-04 20:51:08.912 [info] GET /
teslamate2_1  | 2021-08-04 20:51:08.921 [info] Sent 200 in 8ms
teslamate2_1  | 2021-08-04 20:53:13.077 [info] SIGTERM received - shutting down
teslamate2_1  | 
teslamate2_1  | waiting for postgres at database2:5432
teslamate2_1  | 2021-08-04 20:53:38.662 [info] Migrations already up
teslamate2_1  | 2021-08-04 20:53:45.178 [info] System Info: Erlang/OTP 24 (emu)
teslamate2_1  | 2021-08-04 20:53:45.178 [info] Version: 1.23.7
teslamate2_1  | 2021-08-04 20:53:45.705 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (408.664 ms)
teslamate2_1  | 2021-08-04 20:53:47.681 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (1970.318 ms)
teslamate2_1  | 2021-08-04 20:53:47.681 [info] Refreshed api tokens
teslamate2_1  | 2021-08-04 20:53:47.702 [info] Scheduling token refresh in 5 wk 5 d
teslamate2_1  | 2021-08-04 20:53:47.714 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate2_1  | 2021-08-04 20:53:47.725 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate2_1  | 2021-08-04 20:53:48.951 [info] Starting logger for 'Nova'
teslamate2_1  | 2021-08-04 20:53:48.997 [info] MQTT connection has been established
teslamate2_1  | 2021-08-04 20:53:56.460 car_id=1 [info] Start / :online
teslamate2_1  | 2021-08-04 20:53:56.495 car_id=1 [info] Connecting ...
teslamate2_1  | 2021-08-04 20:53:56.712 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (209.745 ms)
teslamate2_1  | 2021-08-04 20:53:56.750 car_id=1 [info] Charging / SOC: 17% / Thuis
teslamate2_1  | 2021-08-04 20:53:56.751 car_id=1 [info] Disconnecting ...
teslamate2_1  | 2021-08-04 20:54:45.261 [info] GET /
teslamate2_1  | 2021-08-04 20:54:45.300 [info] Sent 200 in 38ms
teslamate2_1  | 2021-08-04 20:57:13.859 [info] GET /charge-cost/18
teslamate2_1  | 2021-08-04 20:57:13.879 [info] Sent 200 in 19ms
teslamate2_1  | 2021-08-04 21:03:58.942 [info] GET /
teslamate2_1  | 2021-08-04 21:03:58.950 [info] Sent 200 in 8ms
teslamate2_1  | 2021-08-04 22:17:38.542 [warn] GET https://owner-api.teslamotors.com/api/1/vehicles/221606540911/vehicle_data -> 504 (10183.681 ms)
teslamate2_1  | 2021-08-04 22:17:38.542 car_id=1 [error] Error / :timeout
teslamate2_1  | 2021-08-04 22:24:45.298 [warn] GET https://owner-api.teslamotors.com/api/1/vehicles/221606540911/vehicle_data -> 504 (10228.541 ms)
teslamate2_1  | 2021-08-04 22:24:45.298 car_id=1 [error] Error / :timeout
teslamate2_1  | 2021-08-05 00:08:21.909 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/221606540911/vehicle_data -> 408 (10559.282 ms)
teslamate2_1  | 2021-08-05 00:08:21.910 [warn] TeslaApi.Error / %{"error" => "https://mothership-api.vn.teslamotors.com:443/vehicles/196220303194 => operation_timedout with 10s timeout", "error_description" => "", "response" => nil}
teslamate2_1  | 2021-08-05 00:08:21.910 car_id=1 [error] Error / :unknown
teslamate2_1  | 2021-08-05 00:51:36.017 car_id=1 [info] Phase correction: 2 -> 3
teslamate2_1  | 2021-08-05 00:51:36.030 car_id=1 [info] Derived efficiency factor: 136.7 Wh/km (10x confirmed)
teslamate2_1  | 2021-08-05 00:51:36.031 car_id=1 [info] Charging / Complete / 40.89 kWh – 238 min
teslamate2_1  | 2021-08-05 00:51:36.034 car_id=1 [info] Start / :online
teslamate2_1  | 2021-08-05 00:51:36.058 car_id=1 [info] Connecting ...
teslamate2_1  | 2021-08-05 00:54:41.646 car_id=1 [info] Suspending logging
teslamate2_1  | 2021-08-05 01:04:23.273 car_id=1 [info] Fetching vehicle state ...
teslamate2_1  | 2021-08-05 01:04:23.866 car_id=1 [info] Start / :asleep
teslamate2_1  | 2021-08-05 01:04:23.878 car_id=1 [info] Disconnecting ...
teslamate2_1  | 2021-08-05 07:33:46.412 car_id=1 [info] Start / :online
teslamate2_1  | 2021-08-05 07:33:46.439 car_id=1 [info] Connecting ...
teslamate2_1  | 2021-08-05 07:36:51.846 car_id=1 [info] Suspending logging
teslamate2_1  | 2021-08-05 07:38:00.171 [info] GET /
teslamate2_1  | 2021-08-05 07:38:00.180 [info] Sent 200 in 8ms
teslamate2_1  | 2021-08-05 07:38:03.046 [info] GET /
teslamate2_1  | 2021-08-05 07:38:03.056 [info] Sent 200 in 9ms
teslamate2_1  | 2021-08-05 07:49:12.338 car_id=1 [info] Fetching vehicle state ...
teslamate2_1  | 2021-08-05 07:49:12.937 car_id=1 [info] Start / :asleep
teslamate2_1  | 2021-08-05 07:49:12.949 car_id=1 [info] Disconnecting ...
…

**Screenshots:**

![TeslaMate Charges print screen 20210805a](https://user-images.githubusercontent.com/67519349/128396859-56bd02f7-89d5-4239-a33f-e5af84311672.png)

TeslaMate Charges print screen

![TeslaMate Charge Details without changing start time 20210805a](https://user-images.githubusercontent.com/67519349/128396882-f41de451-cc94-4faa-8ddf-52369ddd8d5b.png)

TeslaMate Charge Details without changing start time

![TeslaMate Charge Details with changing start time 20210805a](https://user-images.githubusercontent.com/67519349/128396906-22201fff-63d7-414d-9a20-c91782b309ae.png)

TeslaMate Charge Details with changing start time

**Data:**

[charges.csv](https://github.com/adriankumpf/teslamate/files/6940651/charges.csv)
[charging_processes.csv](https://github.com/adriankumpf/teslamate/files/6940653/charging_processes.csv)

**Environment:**

- TeslaMate version: 1.23.7
- Type of installation: Docker
- OS TeslaMate is installed on: Raspberry Pi 4B with all updates installed
- User OS & Browser: Mac OS X 10.15.7, Firefox 90.0.2 (all latest versions)
- Others:

**Comment by dyxyl** [comment] 2021-08-05 21:27
The problem is that you restarted TeslaMate at 22:53 (which is shown as 20:53 UTC in the log). That left an unclosed charging session in the database (id 20 in charging_processes.csv), which is not visible from the Charges dashboard. When Teslamate started again, it made a new charging session (id 21) for the rest of the time.

**Comment by fvanson** [comment] 2021-08-06 05:26
I did not restart TeslaMate. I am 100% sure of that.
I see that the Tesla token got updated at that time, so could it not be that TeslaMate updated the vehicle token while it was still charging? Should maybe token update only be initiated when vehicle is asleep or attempts to go asleep?
Another root cause could have been that my internet connection went down for a minute when I remember back, but this is a situation it should be able to deal with.

**Comment by dyxyl** [comment] 2021-08-06 09:30
Something certainly did restart it:
```
teslamate2_1 | 2021-08-04 20:53:13.077 [info] SIGTERM received - shutting down
teslamate2_1 |
teslamate2_1 | waiting for postgres at database2:5432
teslamate2_1 | 2021-08-04 20:53:38.662 [info] Migrations already up
teslamate2_1 | 2021-08-04 20:53:45.178 [info] System Info: Erlang/OTP 24 (emu)
```
Possibly apt did that, depending on what was upgraded. You could check the logs for the other docker containers to see if they all restarted.

**Comment by fvanson** [comment] 2021-08-07 09:28
When checking /var/log/dpkg.log I believe we can safely assume that 'sudo apt update'  and ' sudo apt full-upgrade' are for blame for interrupting TeslaMate. It matched the time-frame in the TeslaMate log (see log extract below). So this bug can be closed, as root cause is found.

Now, how to solve. Is there any documentation which helps me tap into the database to correct manually data, or is there another way on how to solve?
At an earlier problem I had tried to load only part of TeslaFi data, but that did not work as partial import of TeslaFi data is not supported.

*** dpkg.log extract ***
2021-08-04 22:52:58 startup archives unpack
2021-08-04 22:52:59 upgrade aspell:armhf 0.60.7~20110707-6 0.60.7~20110707-6+deb10u1
2021-08-04 22:52:59 status half-configured aspell:armhf 0.60.7~20110707-6
2021-08-04 22:52:59 status unpacked aspell:armhf 0.60.7~20110707-6
2021-08-04 22:52:59 status half-installed aspell:armhf 0.60.7~20110707-6
2021-08-04 22:52:59 status triggers-pending man-db:armhf 2.8.5-2
2021-08-04 22:52:59 status unpacked aspell:armhf 0.60.7~20110707-6+deb10u1
2021-08-04 22:52:59 upgrade libaspell15:armhf 0.60.7~20110707-6 0.60.7~20110707-6+deb10u1
2021-08-04 22:52:59 status triggers-pending libc-bin:armhf 2.28-10+rpi1
2021-08-04 22:52:59 status half-configured libaspell15:armhf 0.60.7~20110707-6
2021-08-04 22:52:59 status unpacked libaspell15:armhf 0.60.7~20110707-6
2021-08-04 22:52:59 status half-installed libaspell15:armhf 0.60.7~20110707-6
2021-08-04 22:52:59 status unpacked libaspell15:armhf 0.60.7~20110707-6+deb10u1
2021-08-04 22:52:59 upgrade docker-ce-cli:armhf 5:20.10.7~3-0~raspbian-buster 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:52:59 status half-configured docker-ce-cli:armhf 5:20.10.7~3-0~raspbian-buster
2021-08-04 22:52:59 status unpacked docker-ce-cli:armhf 5:20.10.7~3-0~raspbian-buster
2021-08-04 22:52:59 status half-installed docker-ce-cli:armhf 5:20.10.7~3-0~raspbian-buster
2021-08-04 22:53:06 status unpacked docker-ce-cli:armhf 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:53:06 upgrade docker-ce:armhf 5:20.10.7~3-0~raspbian-buster 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:53:06 status half-configured docker-ce:armhf 5:20.10.7~3-0~raspbian-buster
2021-08-04 22:53:06 status unpacked docker-ce:armhf 5:20.10.7~3-0~raspbian-buster
2021-08-04 22:53:06 status half-installed docker-ce:armhf 5:20.10.7~3-0~raspbian-buster
2021-08-04 22:53:06 status triggers-pending systemd:armhf 241-7~deb10u7+rpi1
2021-08-04 22:53:09 status unpacked docker-ce:armhf 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:53:09 upgrade libsndfile1:armhf 1.0.28-6 1.0.28-6+deb10u1
2021-08-04 22:53:09 status half-configured libsndfile1:armhf 1.0.28-6
2021-08-04 22:53:09 status unpacked libsndfile1:armhf 1.0.28-6
2021-08-04 22:53:09 status half-installed libsndfile1:armhf 1.0.28-6
2021-08-04 22:53:09 status unpacked libsndfile1:armhf 1.0.28-6+deb10u1
2021-08-04 22:53:09 startup packages configure
2021-08-04 22:53:09 configure libaspell15:armhf 0.60.7~20110707-6+deb10u1 <geen>
2021-08-04 22:53:09 status unpacked libaspell15:armhf 0.60.7~20110707-6+deb10u1
2021-08-04 22:53:09 status half-configured libaspell15:armhf 0.60.7~20110707-6+deb10u1
2021-08-04 22:53:09 status installed libaspell15:armhf 0.60.7~20110707-6+deb10u1
2021-08-04 22:53:09 configure aspell:armhf 0.60.7~20110707-6+deb10u1 <geen>
2021-08-04 22:53:09 status unpacked aspell:armhf 0.60.7~20110707-6+deb10u1
2021-08-04 22:53:09 status half-configured aspell:armhf 0.60.7~20110707-6+deb10u1
2021-08-04 22:53:10 status installed aspell:armhf 0.60.7~20110707-6+deb10u1
2021-08-04 22:53:10 status triggers-pending dictionaries-common:all 1.28.1
2021-08-04 22:53:10 configure docker-ce-cli:armhf 5:20.10.8~3-0~raspbian-buster <geen>
2021-08-04 22:53:10 status unpacked docker-ce-cli:armhf 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:53:10 status half-configured docker-ce-cli:armhf 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:53:10 status installed docker-ce-cli:armhf 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:53:10 configure libsndfile1:armhf 1.0.28-6+deb10u1 <geen>
2021-08-04 22:53:10 status unpacked libsndfile1:armhf 1.0.28-6+deb10u1
2021-08-04 22:53:10 status half-configured libsndfile1:armhf 1.0.28-6+deb10u1
2021-08-04 22:53:10 status installed libsndfile1:armhf 1.0.28-6+deb10u1
2021-08-04 22:53:10 configure docker-ce:armhf 5:20.10.8~3-0~raspbian-buster <geen>
2021-08-04 22:53:10 status unpacked docker-ce:armhf 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:53:10 status half-configured docker-ce:armhf 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:53:32 status installed docker-ce:armhf 5:20.10.8~3-0~raspbian-buster
2021-08-04 22:53:32 trigproc systemd:armhf 241-7~deb10u7+rpi1 <geen>
2021-08-04 22:53:32 status half-configured systemd:armhf 241-7~deb10u7+rpi1
2021-08-04 22:53:33 status installed systemd:armhf 241-7~deb10u7+rpi1
2021-08-04 22:53:33 trigproc man-db:armhf 2.8.5-2 <geen>
2021-08-04 22:53:33 status half-configured man-db:armhf 2.8.5-2
2021-08-04 22:53:38 status installed man-db:armhf 2.8.5-2
2021-08-04 22:53:38 trigproc libc-bin:armhf 2.28-10+rpi1 <geen>
2021-08-04 22:53:38 status half-configured libc-bin:armhf 2.28-10+rpi1
2021-08-04 22:53:39 status installed libc-bin:armhf 2.28-10+rpi1
2021-08-04 22:53:39 trigproc dictionaries-common:all 1.28.1 <geen>
2021-08-04 22:53:39 status half-configured dictionaries-common:all 1.28.1
2021-08-04 22:53:39 status installed dictionaries-common:all 1.28.1

**Comment by adriankumpf** [comment] 2021-08-31 15:25
All right, thanks for reporting back. I'll close this then.

There is documentation on how to fix drives/charges that were interrupted: https://docs.teslamate.org/docs/maintenance/manually_fixing_data

Manually adding data is not covered yet. Database management tools like TablePlus or pgadmin are helpful to manually add data.

**Closed by adriankumpf** 2021-08-31 15:25 UTC
