### ISSUE TITLE
HomePage not loading after update

### ISSUE THREAD

**Issue by zwuba** [adriankumpf/teslamate#2319] opened 2022-01-14 20:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I just updated my TeslaMate installation on my RaspberryPi to the latest version using Docker (I think its 15.2) and everything was working smooth as usual but when I try to access the Home-Page it's just not loading.
For me it's port 4000  -  http://teslamatepi.local:4000

When accessing port 3000 all dashboards are working fine after logging in.

I guess there shouldn't be a big issue here but it's for sure annoying somehow

### Relevant log output

```shell
Attaching to pi_teslamate_1
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
```

### Type of installation

Docker

### Version

15.2

**Comment by seabie** [comment] 2022-01-14 21:31
I am seeing the same thing, same platform :(

**Comment by adriankumpf** [comment] 2022-01-14 22:48
Duplicate of #2302

**Closed by adriankumpf** 2022-01-14 22:48 UTC
