### ISSUE TITLE
The blue dot has disappeared from the Drive page

### ISSUE THREAD

**Issue by tomS3210** [adriankumpf/teslamate#3043] opened 2023-01-06 17:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,

In Drive details, if i'm right, there was a blue point on the map that moved when you moved the cursor in the graph.

This point was usefull and has disappeared a few month ago.

Could it be possible to fix this ? 

Thanks !

### Expected Behavior

The blue point pust follow the drive on the map when you move your cursor on the graph.

### Steps To Reproduce

Go to Drive
Click on a drive

### Relevant log output

```shell
NA
```

### Screenshots

<img width="1312" alt="Blue Point on Map" src="https://user-images.githubusercontent.com/949584/211066253-6a9a0338-4830-4047-bfc5-da483c08ee00.png">

### Additional data

NA

### Type of installation

Docker

### Version

1.27.1

**Comment by cwanja** [comment] 2023-01-06 17:39
Duplicate of #2770

**Comment by leewillis77** [comment] 2023-01-10 17:12
Also a duplicate of #2866 and #2887

**Closed** 2023-01-13 11:15 UTC
