### ISSUE TITLE
Setup Error Running Wizzy

### ISSUE THREAD

**Issue by grizzlyjere** [adriankumpf/teslamate#59] opened 2019-07-27 22:31 UTC
Using the latest docker image then manually downloaded the english dashboard files to the same location as my docker_compose.yam. When trying to run wizzy (v. 0.6.0), I get an error.

I'm not sure if this is an error with wizzy or teslamate.

I'm running:
`for d in dashboards/en_*; do wizzy export dashboard $(basename $d .json); done`

And getting this error for each file:
```
/usr/local/lib/node_modules/wizzy/src/remote/grafana/exportSrv.js:140
			dashBody.dashboard.id = body_check.dashboard.id;
			                                            ^
TypeError: Cannot read property 'id' of undefined
    at Request.responseHandler [as _callback] (/usr/local/lib/node_modules/wizzy/src/remote/grafana/exportSrv.js:140:48)
    at Request.self.callback (/usr/local/lib/node_modules/wizzy/node_modules/request/request.js:185:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/wizzy/node_modules/request/request.js:1161:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wizzy/node_modules/request/request.js:1083:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)

```

**Comment by cipriani14** [comment] 2019-07-28 03:46
Just ran into this same thing. Did you get around it?

**Comment by adriankumpf** [comment] 2019-07-29 09:04
I could  not yet reproduce that error. As an alternative you can still import the dashboards manually via the Grafana UI. But it's a bit of a hassle unfortunately.

**Comment by ilkkao** [comment] 2019-07-29 18:22
I got somewhat similar error first time when I run wizzy init commands outside of the cloned `teslamate` repo directory. I realised that init commands create a config file or directory and it wasn't searched. Fixed it by doing `cd teslamate && [wizzy init commands] && [that import oneliner script]`

Just in case that's the problem here too.

**Comment by Rfvgyhn** [comment] 2019-07-30 02:24
I ended up using grafana's provisioning capability instead of installing node/npm + wizzy. I wrote a script that does a `git pull` and then copies the json files to my grafana volume which grafana automatically picks up.

See [gist][0] for contents of my scripts and such.

1. Clone this repo
`git clone https://github.com/adriankumpf/teslamate.git teslamate-src`
2. [Update `docker-compose.yml` to include new volume][1]
3. Rebuild grafana container
`docker-compose down && docker-compose up -d`
4. Copy [teslamate.yml][2] to provision volume
`docker cp provisioning/dashboards/teslamate.yml teslamate-grafana:/etc/grafana/provisioning/dashboards`
5. Restart grafana container
`docker restart teslamate-grafana`
6. Run [script][3]
`./update-dashboards.sh`

In the future, you can just run `update-dashboards.sh` to include new changes.

[0]: https://gist.github.com/Rfvgyhn/009f17ac5ea29d2403ed8788a69b7639
[1]: https://gist.github.com/Rfvgyhn/009f17ac5ea29d2403ed8788a69b7639#file-docker-compose-yml
[2]: https://gist.github.com/Rfvgyhn/009f17ac5ea29d2403ed8788a69b7639#file-teslamate-yml
[3]: https://gist.github.com/Rfvgyhn/009f17ac5ea29d2403ed8788a69b7639#file-update-dashboards-sh

**Comment by cipriani14** [comment] 2019-07-30 21:10
I ended up importing them manually, but only did the en_ versions. Every dashboard has a red ! In the upper corner, each with its own error message. For example, trips has: 

Trips 
No data to show 
pq: function convert_km(double precision, unknown) does not exist

Any idea on where I went wrong?

**Comment by adriankumpf** [comment] 2019-07-30 21:12
Does reselecting the temperature / length unit help?

**Comment by cipriani14** [comment] 2019-07-30 21:15
![E7E7A18B-7938-46A4-9EAE-835A8DFB4F98](https://user-images.githubusercontent.com/375853/62165951-d190fc80-b2dc-11e9-87b8-ae61e0b92379.jpeg)

It doesn’t appear to.

**Comment by adriankumpf** [comment] 2019-07-30 21:22
Okay, could you restart the container e.g. with `docker-compose restart` to make sure the migrations are applied?

**Comment by cipriani14** [comment] 2019-07-30 21:25
I’m 99% sure it’s something I did. That didn’t fix it either. Here’s another example. 
![16186506-958A-461C-8CFC-F868F9DFD2C8](https://user-images.githubusercontent.com/375853/62166555-4f093c80-b2de-11e9-86a3-d229005bb2f9.jpeg)

**Comment by adriankumpf** [comment] 2019-07-30 21:29
This is actually expected. See https://github.com/adriankumpf/teslamate#faq The other dashboards should work out of the box though

**Comment by adriankumpf** [comment] 2019-07-30 21:32
What happens when you append the following query parameters to the url of the `Trips` dashboard: `&var-car=1&var-temp_unit=F&var-length_unit=mi`?

**Comment by cipriani14** [comment] 2019-07-30 21:38
Same error message as before.

**Comment by adriankumpf** [comment] 2019-07-30 21:49
I'm really running out of ideas. Is anybody else seeing those error messages?

Does the at least the `Position` dashboard work?

**Comment by andrewfoster** [comment] 2019-07-30 21:54
Did you run 'wizzy init' in the parent directory of the 'dashboards'
directory?

**Comment by Rfvgyhn** [comment] 2019-07-30 21:57
@adriankumpf What are your thoughts on creating a custom grafana image that auto provisions the datasource and dashboards?

**Comment by adriankumpf** [comment] 2019-07-30 22:04
@Rfvgyhn oh, yeah, that would make the installation way easier for many. Good idea.

**Comment by adriankumpf** [comment] 2019-07-31 00:37
FYI: I started a new branch (#70) that will add the custom grafana image

**Comment by cipriani14** [comment] 2019-07-31 01:32
Position works. 

I believe I tried the init command prior to getting the error message that’s in this thread above.

**Comment by adriankumpf** [comment] 2019-07-31 10:45
The custom grafana image is now available (as beta). I really recommend to use it instead of manually provisioning the dashboards since upgrading to a new version gets dramatically easier. I updated the README accordingly. Thanks @Rfvgyhn for the idea and your initial work!

Closing this for now

**Closed by adriankumpf** 2019-07-31 10:45 UTC

**Comment by cipriani14** [comment] 2019-07-31 12:52
That worked for me. thank you!
