### ISSUE TITLE
Car name being set to "Null" this week

### ISSUE THREAD

**Issue by aiden-cat** [adriankumpf/teslamate#3236] opened 2023-06-09 23:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Starting earlier this week I've noticed the car name resetting to "null" - restarting my raspberry pi will fix this temporarily.  I haven't updated anything this week and it seems it just started this week.  Anyone have an idea?  

Looks like not an isolated incident either report here: [119480](https://teslamotorsclub.com/tmc/threads/teslamate-megathread.191537/page-137#post-7660108)

### Relevant log output

```shell
N/A
```

### Type of installation

Docker

### Version

1.27.2

**Comment by cwanja** [comment] 2023-06-09 23:59
Duplicate of #3183

**Comment by aiden-cat** [comment] 2023-06-10 00:03
> Duplicate of #3183

oh didn't know it's a long standing issue!  Will delete this issue

**Comment by cwanja** [comment] 2023-06-10 00:04
It might not be entirely different? Feel that issue might have gotten hijacked with the issues recently starting this week.

**Closed** 2023-06-10 00:03 UTC
