### ISSUE TITLE
Time driven not correct per year

### ISSUE THREAD

**Issue by viorelovidiu** [adriankumpf/teslamate#4373] opened 2024-11-11 09:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Every time when I go to Statistics Dashboard and set it as yearly, Time driven value is not correct.
for 2024 it says 46 hours but once I click on year 2024 I have one month as time driven which is correct:
Same issue with year 2023 where the actual time driven is one month and one week.

Thank you

### Expected Behavior

To show correct time driven value in Statistics Dashboard

### Steps To Reproduce

Go to Dashboard -> select Statistics -> Select Period value as "year"

### Relevant log output

```shell
no relevant outlook as there is no error.
```

### Screenshots

![image](https://github.com/user-attachments/assets/c0cfca48-a457-4590-a8a3-4e356025c33a)
![image](https://github.com/user-attachments/assets/77126be2-242d-47f6-9e7a-31a419a3ac21)

### Additional data

no relevant outlook as there is no error.

### Type of installation

Docker

### Version

1.31.1

**Comment by DrMichael** [comment] 2024-11-11 14:27
Hmmm, I don't see driven time in the Trip dashboard.

But the driven times in Statistics are obviously wrong, it would mean an average speed of 511km/h... Can you show the raw data for that dashboard?

**Comment by swiffer** [comment] 2024-11-12 05:13
Duplicate of #4268, fixed in open PR

**Closed as not planned** 2024-11-12 16:02 UTC
