### ISSUE TITLE
[error] Vehicle Error: Vehicle is offline

### ISSUE THREAD

**Issue by tleegaard** [adriankumpf/teslamate#1472] opened 2021-03-24 11:30 UTC
**Describe the bug**
I notice lots of "Vehicle is offline" in the log. Is this normal behavior?

**Expected behavior**
No errors in the log

**How to reproduce it (as minimally and precisely as possible)**:

**Relevant entries from the logs**

```
2021-03-24 12:17:38.080 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:17:55.117 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (243.364 ms)
2021-03-24 12:18:09.293 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:18:25.645 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (290.049 ms)
2021-03-24 12:18:39.294 car_id=1 [info] Received stream data: :inactive
2021-03-24 12:18:40.806 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:18:56.184 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (250.906 ms)
2021-03-24 12:19:12.015 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:19:26.641 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (230.297 ms)
2021-03-24 12:19:43.206 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:19:57.128 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (248.888 ms)
2021-03-24 12:20:14.409 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:20:27.609 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (247.203 ms)
2021-03-24 12:20:45.591 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:20:58.082 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (249.825 ms)
2021-03-24 12:21:03.183 [info] GET /
2021-03-24 12:21:03.195 [info] Sent 200 in 11ms
2021-03-24 12:21:13.264 [info] GET /settings
2021-03-24 12:21:13.282 [info] Sent 200 in 17ms
2021-03-24 12:21:16.809 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:21:28.582 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (257.403 ms)
2021-03-24 12:21:47.995 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:21:59.056 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (254.540 ms)
2021-03-24 12:22:19.279 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:22:29.535 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (244.885 ms)
2021-03-24 12:22:50.490 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:23:00.038 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (253.946 ms)
```
And after waking up the car with the Tesla app
```
2021-03-24 12:31:42.445 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:32:09.996 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (285.742 ms)
2021-03-24 12:32:13.660 [error] Vehicle Error: Vehicle is offline
2021-03-24 12:32:19.586 [info] GET /
2021-03-24 12:32:19.596 [info] Sent 200 in 10ms
2021-03-24 12:32:40.485 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (261.758 ms)
2021-03-24 12:32:55.679 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/redacted/vehicle_data -> 408 (9249.348 ms)
2021-03-24 12:32:55.916 car_id=1 [warn] Discarded incomplete fetch result
2021-03-24 12:33:06.759 car_id=1 [info] Vehicle came back online after 271 min
2021-03-24 12:33:06.759 car_id=1 [info] Start / :online
2021-03-24 12:33:23.834 [info] GET /
2021-03-24 12:33:23.844 [info] Sent 200 in 9ms
2021-03-24 12:35:52.476 [info] GET /
2021-03-24 12:35:52.488 [info] Sent 200 in 12ms
2021-03-24 12:35:55.103 car_id=1 [info] Suspending logging [Triggered manually]
2021-03-24 12:37:27.709 [info] GET /
2021-03-24 12:37:27.722 [info] Sent 200 in 13ms
2021-03-24 12:48:11.032 [info] GET /
2021-03-24 12:48:11.042 [info] Sent 200 in 9ms
2021-03-24 12:54:31.796 car_id=1 [info] Fetching vehicle state ...
2021-03-24 12:54:32.658 car_id=1 [info] Start / :asleep
2021-03-24 12:54:32.671 car_id=1 [info] Disconnecting ...
```

**Environment**

- TeslaMate version: 1.21.6
- Type of installation: [Home Assistant Addon](https://github.com/matt-FFFFFF/hassio-addon-teslamate)
- OS TeslaMate is installed on: RPI
- User OS & Browser: Multiple
- Others: MCU1 with settings as described here https://docs.teslamate.org/docs/faq/

**Comment by adriankumpf** [comment] 2021-03-25 16:04
No, that's not a bug. If the Tesla API reports your car as offline, TeslaMate has no control over that. 

Moving this to [🙏 Q&A](https://github.com/adriankumpf/teslamate/discussions/categories/q-a) …

**Closed** 2021-03-25 16:04 UTC
