### ISSUE TITLE
What happend to Vampire drain?

### ISSUE THREAD

**Issue by airmaxx** [adriankumpf/teslamate#450] opened 2020-02-14 20:15 UTC
**Describe the bug**

Since 27.1.20 vampire drain stops showing values: TR Loss | kWh, Ø-Power and TR Loss / h only show a minus, while there a snwoflake icon in one column from that date on.

**Expected behavior**

See the loss that occured

**Operating environment**

- TeslaMate Version: v1.15.1
- Type of installation: Manual
- OS: Ubuntu

**Comment by ArnoPW** [comment] 2020-02-14 21:17
Same here in v1.16. As soon as a snowflake is shown, no other information is shown. I have some with and some without snowflakes. All without snowflake show values, with snowflakes all minus symbols.

![image](https://user-images.githubusercontent.com/52374663/74568192-baafb000-4f77-11ea-8070-a61f7d625f4f.png)

**Comment by Koofteh123** [comment] 2020-02-15 03:31
I'm seeing some data disappearing in vampire drain. For example my longest sleep in the table was 2.x days but now the longest entry is only 12 hours. Does anyone know what is happening?

**Comment by olexs** [comment] 2020-02-15 09:00
> I'm seeing some data disappearing in vampire drain. For example my longest sleep in the table was 2.x days but now the longest entry is only 12 hours. Does anyone know what is happening?

The "vampire drain" view is set to last 90 days per default. If your longest sleep is older than that, it'll disappear from view. You can change the date range in the top right corner of Grafana.

**Comment by Koofteh123** [comment] 2020-02-15 09:09
> > I'm seeing some data disappearing in vampire drain. For example my longest sleep in the table was 2.x days but now the longest entry is only 12 hours. Does anyone know what is happening?
> 
> The "vampire drain" view is set to last 90 days per default. If your longest sleep is older than that, it'll disappear from view. You can change the date range in the top right corner of Grafana.

Thanks for the reply. I know about that window but still missing entries. I wonder if some are being hidden automatically? When I restore w backup I see the entry but it disappears by itself.

**Comment by adriankumpf** [comment] 2020-02-16 11:53
> I wonder if some are being hidden automatically?

I see no reason why that should happen. If the period is selected accordingly, the entry should be visible. Have you ever tried scrolling down the table? :)

**Comment by adriankumpf** [comment] 2020-02-16 11:54
Regarding the actual issue: this is a duplicate of https://github.com/adriankumpf/teslamate/issues/404.

> The vampire drain is calculated based on the lost range. If the battery cools down due to cold weather and thus the range is artificially reduced, it is not possible to determine the Vampire drain accurately.
> 
> See #390 for solutions on how to display those values anyway. However, I would recommend to use the SOC difference if the consumption values cannot be determined instead of relying on incorrect data.

**Closed by adriankumpf** 2020-02-16 11:54 UTC
