### ISSUE TITLE
[Safari BUG] Persistent refresh with latest Safari 13.1 due to Basic Auth

### ISSUE THREAD

**Issue by SemoTech** [adriankumpf/teslamate#643] opened 2020-04-24 18:24 UTC
**Describe the bug**

While accessing latest teslamate v1.19.1 from latest Safari v13.1 on Mac OS Mojave, and after the initial login, all pages including home, geo-fences and settings refresh in the browser non-stop and make teslamate unusable.   Firefox v75 and Google Chrome v81.0.4044.122 confirmed working fine, self-refresh issue seems limited to Safari

**To Reproduce**

Try to use latest teslamate with Safari 13.1

**Expected behavior**

Should work the same on all major browsers!

**Relevant entries from the logs**

n/a

**Operating environment**

- TeslaMate Version: v1.19.1
- Type of installation = Docker (Advanced Docker install (Traefik, Let’s Encrypt, HTTPS, HTTP Basic Auth))
- Docker version = 19.03.7
- Server OS: CentOS 7
- Browser:  Safari 13.1
- Client OS:  Mojave 10.14.6

**Comment by tacotran** [comment] 2020-04-24 19:34
Check out this comment (follow the bug report). It seems to be an unfixed bug regarding Safari + basic auth + websockets

**Comment by SemoTech** [comment] 2020-04-24 20:39
@tacotran indeed.  However never had this issue (or noticed this issue) before now.

**Comment by adriankumpf** [comment] 2020-04-25 11:16
> **Expected behavior**
> 
> Should work the same on all major browsers!

I agree. But the bug is in Safari, as @tacotran has correctly noticed, and has not been fixed for 8 years. Direct access to the web interface without basic authentication (from your home network) works in Safari. There are also alternatives to basic auth (#413) but that is not directly related to TeslaMate. That's why I'll close this.

_Duplicate of #415_

**Closed by adriankumpf** 2020-04-25 11:16 UTC

**Comment by SemoTech** [comment] 2020-04-25 17:45
Hi @adriankumpf One more update on this, it seems the same issue that plagues Safari 13.1 on MacOS are also present in ALL the mobile browsers I test in iOS 13.3.  Chrome, Safari, Brave, Firefox, etc... all cannot use the teslamate web interface!

**Comment by adriankumpf** [comment] 2020-04-25 20:43
Yes, that's because Safari (and all other browsers) on iOS use the same WebKi engine as Safari on macOS. 

As a workaround, you could configure Traefik so that the WebSocket traffic is not required to use basic auth:

```diff
       - "traefik.http.middlewares.auth.basicauth.usersfile=/auth/.htpasswd"
       - "traefik.http.routers.teslamate-insecure.rule=Host(`${FQDN_TM}`)"
       - "traefik.http.routers.teslamate-insecure.middlewares=redirect"
+      - "traefik.http.routers.teslamate-ws.rule=Host(`${FQDN_TM}`) && Path(`/live/websocket`)"
+      - "traefik.http.routers.teslamate-ws.entrypoints=websecure"
+      - "traefik.http.routers.teslamate-ws.tls"
       - "traefik.http.routers.teslamate.rule=Host(`${FQDN_TM}`)"
       - "traefik.http.routers.teslamate.middlewares=auth"
       - "traefik.http.routers.teslamate.entrypoints=websecure"
```

**Comment by SemoTech** [comment] 2020-04-25 20:58
Thanks @adriankumpf I made the changes for Traffic under Teslamate in docker-compose.yml but now getting "bad gateway" when accessing teslamate.domain.com.  Here is the entire Traefik section in the teslamate section of docker-compose.yml:

```
   labels:
      - 'traefik.enable=true'
      - 'traefik.port=4000'
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth/.htpasswd"
      - "traefik.http.routers.teslamate-insecure.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate-insecure.middlewares=redirect"
      - "traefik.http.routers.teslamate-ws.rule=Host(`${FQDN_TM}`) && Path(`/live/websocket`)"
      - "traefik.http.routers.teslamate-ws.entrypoints=websecure"
      - "traefik.http.routers.teslamate-ws.tls"
      - "traefik.http.routers.teslamate.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate.middlewares=auth"
      - "traefik.http.routers.teslamate.entrypoints=websecure"
      - "traefik.http.routers.teslamate.tls.certresolver=tmhttpchallenge"

```

**Comment by baylanger** [comment] 2020-04-26 14:01
Can you try again w/ Safari 13.1.1?  Seems to finally work.

![2020-04-26_09-56-14](https://user-images.githubusercontent.com/5240348/80309744-d4097f80-87a4-11ea-85e6-356a55623198.png)

**Comment by baylanger** [comment] 2020-04-26 17:26
Never mind my previous comment, my Safari history picked "http" and I didn't realize.  Safari is still broken, I use Firefox and believe Chrome likely works as well.

**Comment by SemoTech** [comment] 2020-04-26 17:26
@baylanger There is no Safari 13.1.1 for Mojave 10.14.6.  Apple's [release notes page](https://developer.apple.com/documentation/safari_release_notes) shows latest version is Safari 13.1, there is no mention of 13.1.1

I am hoping @adriankumpf has a fix for the Traefik options he provided above, as that will hopefully also fix the mobile browsers!

**Comment by baylanger** [comment] 2020-04-26 17:32
Catalina beta has Safari 13.1.1 but like I mentioned minutes ago the bug still hasn't been fixed.

The day an Apple employee installs Teslamate and complains it's not working, maybe it will get fix? 🤔

**Comment by SemoTech** [comment] 2020-04-26 18:09
I hear ya @baylanger Let's hope one of them does :-). Intestinally your interface for teslamate on your sleeping TM3 that you posted above has additional info, like the 3 buttons on the top right and the "Charge Limit" info.  I am running latest teslamate v1.19.2 w/ same firmware, but am missing that info for my sleeping TM3. See below.  Any idea why?

![image](https://user-images.githubusercontent.com/1452100/80315697-47bc8400-87c7-11ea-867b-c1efd7dd003c.png)

Again, I was excited to see the feedback from @adriankumpf posted above, and if he can clarify/fix the Traefik options he provided we may have a temporary workaround.

**Comment by DrJohnM61** [comment] 2020-04-26 18:19
> Never mind my previous comment, my Safari history picked "http" and I didn't realize.  Safari is still broken, I use Firefox and believe Chrome likely works as well.

I have also gad this issue and cleared web cache/cookies to fix it but I also see this comment from a search on the subject:

<quote>
HSTS Policy is now included in Safari's stored website data, and you can remove {webaddress} data to clear this issue.


command + ,
Privacy -> Manage Website Data...
Search {webaddress}
Click Remove


The trick here is that, at some point, you visited a {webaddress} with an HSTS policy, which means that it will never attempt to visit the HTTP version. This is a great security feature for websites generally, but problematic for local development.
<endquote>

**Comment by SemoTech** [comment] 2020-04-26 18:26
@DrJohnM61 how does one figure out which website had an HSTS policy in order to remove it?  I checked and teslamate was NOT in my list.   Is there a way to remove any/all?

**Comment by tacotran** [comment] 2020-04-26 18:54
Since your browser defaulted to http and you were able to use https, there won't be an HSTS policy on that domain for you.

You should probably just not RP on port 80 and leave it open exclusively for LetsEncrypt traffic.

**Comment by SemoTech** [comment] 2020-04-28 16:49
Does anyone have a fix for the Traefik section in the teslamate area of docker-compose.yml that Adrian posted but does not work?

**Comment by tacotran** [comment] 2020-04-30 18:13
> Does anyone have a fix for the Traefik section in the teslamate area of docker-compose.yml that Adrian posted but does not work?

This may sound a little silly, but if you copied and pasted it from here, did you try re-typing it out manually? I've had quite awful experiences copying stuff (especially backticks) from various sources.

**Comment by SemoTech** [comment] 2020-04-30 19:13
@tacotran nothing is silly when it comes to code :-) 

I copied and pasted and then tried it manually too.  That's why I posted the full block of the Traefik section in the teslamate area of docker-compose.yml file.  Here it is again below.  

If you try it does it work for you or fail with the "bad gateway" error like it did for me?

```
labels:
      - 'traefik.enable=true'
      - 'traefik.port=4000'
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth/.htpasswd"
      - "traefik.http.routers.teslamate-insecure.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate-insecure.middlewares=redirect"
      - "traefik.http.routers.teslamate-ws.rule=Host(`${FQDN_TM}`) && Path(`/live/websocket`)"
      - "traefik.http.routers.teslamate-ws.entrypoints=websecure"
      - "traefik.http.routers.teslamate-ws.tls"
      - "traefik.http.routers.teslamate.rule=Host(`${FQDN_TM}`)"
      - "traefik.http.routers.teslamate.middlewares=auth"
      - "traefik.http.routers.teslamate.entrypoints=websecure"
      - "traefik.http.routers.teslamate.tls.certresolver=tmhttpchallenge"
```

**Comment by tacotran** [comment] 2020-04-30 20:56
I don't use Traefik because I already had a pretty extensive apache/httpd setup prior to using TeslaMate.

I also switched away from using Basic Auth and slapped together a basic redirect login page so that I could save my password in my instead of logging in to the popup every single time.

**Comment by SemoTech** [comment] 2020-05-01 02:11
@tacotran That sounds like a nice workaround, care to share the details on how you did the login page and what had to change in the teslamate config file to make it work?

**Comment by tacotran** [comment] 2020-05-01 04:45
@SemoTech Sure. Bonus Grafana under subpath so you don't need two FQDNS.

Follow the apache basic conf and in docker-compose.yml under grafana/environment:

```diff
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
-     - GF_SERVER_ROOT_URL=https://${FQDN_GRAFANA}
+     - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
+     - GF_SERVER_SERVE_FROM_SUB_PATH=true
```

From the teslamate.conf for apache:

```diff
+       Alias "/auth" "/path/to/your/webroot"
+       ProxyPass /auth !
        ProxyPass /live/websocket ws://127.0.0.1:4000/live/websocket
        ProxyPassReverse /live/websocket ws://127.0.0.1:4000/live/websocket
+       ProxyPass /grafana http://127.0.0.1:3000
+       ProxyPassReverse /grafana http://127.0.0.1:3000
        ProxyPass / http://127.0.0.1:4000/
        ProxyPassReverse / http://127.0.0.1:4000/
```

Same file:
```diff
        <Proxy *>
-           Authtype Basic
+           Authtype Form
+           AuthFormProvider file
+           SessionCookieName session path=/
+           AuthFormLoginRequiredLocation "https://teslamate.domain.com/auth/login.html"
+           ErrorDocument 401 "/auth/login.html"
            Authname "Password Required"
            AuthUserFile /etc/apache2/.htpasswd
            Require valid-user
        </Proxy>
```
You'll need to drop your login.html in "/path/to/your/webroot". Here's a really basic sample below, or you can find a free one online to drop in.

```
<html>
	<head>
		<title>Login page</title>
	</head>
	<body>
		<form method="POST" action="">
			User: <input type="text" name="httpd_username" value="" />
			Pass: <input type="password" name="httpd_password" value="" />
			<input type="submit" name="login" value="Login" />
		</form>
	</body>
</html>
```

**Comment by SemoTech** [comment] 2020-05-02 22:03
Than you @tacotran very interesting and promising.  Only snag is that since I was unable to get this to work at all in a cPanel/WHM environment (hence why I posted [HERE](https://github.com/adriankumpf/teslamate/issues/644#issue-606591074) asking for some help), I ended up using a raw CentOS 7 compute instance with docker pre-installed, and followed the simpler [Traefik](https://docs.teslamate.org/docs/guides/traefik) tutorial for TeslaMate.  Therefore I have no  "teslamate.conf for apache" file, as there is no Apache.  Could you be so kind as to adjust the instructions for this configuration? Thanks!

**Comment by tacotran** [comment] 2020-05-03 04:25
Again, I have zero experience with Traefik. From a quick glance the only other two auth options it provides are ForwardAuth and DigestAuth and neither of those work with this method.

**Comment by SemoTech** [comment] 2020-05-03 16:37
@tacotran No worries, all your help is much appreciated.  I managed to get it to work perfectly with the changes Adrian [posted](https://github.com/adriankumpf/teslamate/issues/643#issuecomment-619438150) and updated the [main docs](https://docs.teslamate.org/docs/guides/traefik) with.  The "Bad Gateway" error was apparently related to browser caching, and is now resolved.  

Now if I could only find someone to get this to work in cPanel with User Namespaces enabled, I can stop paying for 3rd party hosting...

**Comment by GaPhi** [comment] 2020-05-03 18:48
Hi @tacotran, I have an issue to let TM work in a subpath of an existing web server.

I succeeded with grafana (it works like a charm) thanks to the same tricks as you in this thread but those possibilities seem to be natively absent in teslamate.

Is there any trick/workaround to let Apache2/Proxy transform URL with an leading /teslamate subpath (or any other approach that works) ?

Thanks in advance !
