### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Kxa422** [adriankumpf/teslamate#1941] opened 2021-09-01 15:48 UTC
**Describe the bug**

When I try to login, after the username and password the following error message appear

Error: Captcha does not match

**Expected behavior**

Go to the captcha page or 2FA part.

**How to reproduce it (as minimally and precisely as possible)**:

Access the login page
Enter username and password
Click Sign in

**Screenshots**

![image](https://user-images.githubusercontent.com/8321111/131702681-7693661f-91f4-49c6-82bb-0298d1ed62a1.png)

- TeslaMate version: 1.23.7 
- Type of installation: Docker
- OS TeslaMate is installed on: Raspberry Pi
- User OS & Browser: Chrome
- Others:

**Comment by adriankumpf** [comment] 2021-09-01 18:50
Duplicate of #1888. Update to the latest TeslaMate version.

**Closed by adriankumpf** 2021-09-01 18:50 UTC
