### ISSUE TITLE
Teslamate Health Check fails repeatedly

### ISSUE THREAD

**Issue by krelltunez** [adriankumpf/teslamate#1370] opened 2021-02-21 03:01 UTC
**Describe the bug**

I have two cars on my Tesla account.  Both show in Teslamate and had been rock solid stable for months.  Recently, one car started going offline (Health check failed warning) intermittently.  Now both cars are doing it.  They will not stay online for long, and the ONLY thing I can do to get them to come back is to restart the container.  When this happens, the Tesla app is fine - shows both cars' statuses, location, etc.

**Expected behavior**

Previously, the cars would only show the Health check failed warning when something went wonky on the Tesla side (which is how this is supposed to work).  Now, it seems as if this problem is on the Teslamate side.

**Environment**

- TeslaMate version: 1.21.4
- Type of installation: Docker 
- OS TeslaMate is installed on: QNAP
- User OS & Browser: Windows 10 Chrome
- Others: N/A

I'll provide logs if needed but first I wanted to see if anyone else is experiencing this.  I'm not an experienced Docker user so I'm not super confident in pulling logs, diagnosing the problem on my end, etc.

**Comment by dutenhnj** [comment] 2021-02-21 03:31
Duplicate of #1369

**Closed** 2021-02-21 09:49 UTC
Labels: duplicate
