### ISSUE TITLE
Upgrade Grafana to 8.2 version

### ISSUE THREAD

**Issue by tydoo** [adriankumpf/teslamate#2134] opened 2021-11-09 10:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upgrade grafana from 7.5.10 to latest version

### Type of installation

Docker

### Version

v1.24.2

**Comment by adriankumpf** [comment] 2021-11-09 17:02
Duplicate of https://github.com/adriankumpf/teslamate/issues/1728

**Closed by adriankumpf** 2021-11-09 17:02 UTC
