### ISSUE TITLE
TeslaMate web interface not working on Safari

### ISSUE THREAD

**Issue by Geitenijs** [adriankumpf/teslamate#466] opened 2020-02-18 22:22 UTC
**Describe the bug**

I'm not able to interact with anything on the TeslaMate dashboard except for the header on Safari for macOS and iOS. This includes the login form, all buttons/switches etc.
On my Mac I see a blue loading icon as shown on the screenshot.

Everything works fine when using Firefox on the same Mac.

Might be related to #415 

**Screenshots**

<img width="626" alt="Screenshot 2020-02-18 at 23 13 17" src="https://user-images.githubusercontent.com/40541903/74782834-910ec580-52a4-11ea-8b1e-74f7be13c7af.png">

**Operating environment**

- TeslaMate Version: v1.16
- Type of installation: Docker advanced Traefik
- OS: Ubuntu 18.04

**Comment by adriankumpf** [comment] 2020-02-19 10:40
Duplicate of #415. It's a bug in Safari: https://github.com/adriankumpf/teslamate/issues/415#issuecomment-587158745

**Closed by adriankumpf** 2020-02-19 10:40 UTC

**Comment by adriankumpf** [comment] 2020-02-19 11:05
For possible alternatives for basic auth see #413

**Comment by baylanger** [comment] 2020-04-26 14:05
fyi #415 seems fixed in Safari 13.1.1

![2020-04-26_09-56-14](https://user-images.githubusercontent.com/5240348/80309837-5abe5c80-87a5-11ea-9d49-537ff37afabf.png)
