### ISSUE TITLE
Add tags to drives

### ISSUE THREAD

**Issue by cessnail** [adriankumpf/teslamate#842] opened 2020-07-18 13:35 UTC
**What would you like to be added**:
I would like to add tags to log drives and add tags to them. This way, I can tag, filter and export drives as 'business' or 'personal' (or any other tag).

**Why is this needed**:
A detailed drive log will be used for tax filing and company administration.

**Additional context**:

**Comment by adriankumpf** [comment] 2020-07-26 11:00
Duplicate of #505

**Closed by adriankumpf** 2020-07-26 11:00 UTC
Labels: duplicate, request
