### ISSUE TITLE
Lots of small charges

### ISSUE THREAD

**Issue by gaardiolor** [adriankumpf/teslamate#323] opened 2019-12-28 17:52 UTC
Hello,

I'm using Teslamate 1.13.2 . 

Today I've charged from ~13% until ~81% at a Tesla supercharger in 2 sessions (moved to a free 'pair' when it became available). In grafana the second session got split in a lot of small, incompleted sessions.

![image](https://user-images.githubusercontent.com/22920143/71645461-306a0000-2cd9-11ea-9aa2-c7606e8eb80b.png)

Why .. ? And can I fix this in the database somehow ?

**Comment by ivaxdr** [comment] 2019-12-31 09:07
I have the same problem reported. Also I ‘m using 1.13.2 because 1.14.1 crash on docker, only the teslamate container.

**Comment by adriankumpf** [comment] 2020-01-02 20:33
This looks like a problem with the logging of charges. Please add the teslamate container logs of that time. To get the Docker container logs, for example, use the following command: `docker-compose logs teslamate`.

**Comment by adriankumpf** [comment] 2020-01-02 20:33
> Also I ‘m using 1.13.2 because 1.14.1 crash on docker, only the teslamate container.

@ivaxdr, does the issue persist after a `docker-compose pull && docker-compose up`? If so, you should open a new issue (“new issue” -> “Bug”) to have it fixed.

**Comment by ivaxdr** [comment] 2020-01-02 21:28
After a docker-compose pull && docker-compose up it persist, I downgraded to 1.13 and also I added "phase_correction" to the table geofences (but this is another problem)

**Comment by gaardiolor** [comment] 2020-01-03 13:45
@adriankumpf see attachment for the logs!
[teslamate_log.txt](https://github.com/adriankumpf/teslamate/files/4019273/teslamate_log.txt)

**Comment by adriankumpf** [comment] 2020-01-06 18:42
Duplicate of #343

**Closed** 2020-01-06 18:42 UTC
Labels: bug

**Comment by gaardiolor** [comment] 2020-01-07 16:06
@adriankumpf any easy way to clean up those old charges ?
`delete from charging_processes where end_date is null;` or will that mess up db consistency ? The COUNT wouldn't match charging_processes_id_seq for example. Thanks

**Comment by adriankumpf** [comment] 2020-01-14 20:02
Yup, `DELETE FROM charging_processes WHERE end_date IS NULL;` is the way to go. If that fails with a foreign key constraint violation delete the corresponding entries (`charging_process_id`) from the `charges` table.
