### ISSUE TITLE
Drive details missing

### ISSUE THREAD

**Issue by bpankz** [adriankumpf/teslamate#390] opened 2020-01-25 02:38 UTC
**Describe the bug**

On the Drives dashboard, consumption and efficiency are missing data, only show a -
On the Drive Details dashboard, distance, energy used and duration is missing data.

**To Reproduce**

Open Drives dashboard, click on one of the drives.

**Expected behavior**

Should show the information in the column

**Screenshots**
Drives dashboard
![image](https://user-images.githubusercontent.com/54423181/73115213-f3b4b180-3ef0-11ea-9550-8928e574a2d4.png)

drive details dashboard
![image](https://user-images.githubusercontent.com/54423181/73115193-d5e74c80-3ef0-11ea-908b-64373de0f6b1.png)

**Operating environment**

- TeslaMate Version: v1.15.0
- Type of installation: Manual
- OS: Ubuntu Server 19.10
- Grafana: 6.5.3

**Comment by adriankumpf** [comment] 2020-01-25 15:08
>  On the Drive Details dashboard, distance, energy used and duration is missing data.

Good catch. Fixed with v1.15.1!

> On the Drives dashboard, consumption and efficiency are missing data, only show a -

It's not a bug, it's a feature! ;) Those values are now hidden if we know that they are wrong anyway because they could not be determined accurately, e.g. because the trip was too short or because of cold weather (reduced range).

**Comment by bpankz** [comment] 2020-01-25 15:50
Are the efficiency values being hidden a way to not skew the overall efficiency calculations? And is there a minimum amount of regen required before it calculates? I read the consumption column as wh/mi instead of kwh so it still helps me to see how the numbers compare to "normal".

I agree without knowing how cold soaked the battery is, it could have some wildly high numbers but for 15 and 20+ mile drives they're accurate to what the car did during that drive compared to what it's capable of doing in ideal conditions. Or am I off on how those numbers are calculated?

**Comment by BabyYeggie** [comment] 2020-01-27 06:35
Any chance of enabling the values or setting an efficiency range between 10-200%? It's completely normal for people who live in cold climates to have the battery be cold soaked nearly 100% of the time. If the efficiency calculations are turned off if the battery is cold soaked, then we'll have a lot of missing data. I've had usage as high as 1500wh/km for short trips, where I left my driveway, drove down the road, then turned around.

**Comment by adriankumpf** [comment] 2020-01-27 16:28
> Are the efficiency values being hidden a way to not skew the overall efficiency calculations? 

For now the efficiency values are still included in the overall calculations on the 'Efficiency' dashboard. 

>  I read the consumption column as wh/mi instead of kwh so it still helps me to see how the numbers compare to "normal".

The kWh values are based on the (rated/ideal) range difference per drive. E.g. to get the consumption per 100 km/mi:

```
rated_range_diff * rated_consumption / distance * 100
```

As the range is often reduced in cold weather at the beginning of a trip, the 'range_difference' gets distorted, because as the battery gets warmer, we seem to get more range. On many of my cold weather drives, the efficiency was significantly positive, which is only because the 'range' difference was smaller than it should have been.

As I see it, it makes no sense to display the efficiency figures under these conditions. We might as well display random values. However, as it is currently implemented, the values are still displayed for some drives. For example, if there is no more range reduction at the end of a drive. In this case, the drive was probably long enough to warm up the battery, making the difference less significant overall.

**Comment by bruendi** [comment] 2020-01-27 22:39
I have a question about the drives dashboard.
Might be the wrong thread to ask for, but for me it sounds at least not 100% wrong to ask here.

In the previous versions < 1.15.x on the drives dashboard there where the start and end odometer values visible, which was grate for the use as driver's logbook to bill the milage allowance to the company I am working for. Is there an easy way to show these values again or to introduce a new dashboard (i.e. driver's logbook) for this issue?

**Comment by bpankz** [comment] 2020-01-28 00:55
> However, as it is currently implemented, the values are still displayed for some drives. For example, **_if there is no more range reduction at the end of a drive_**. In this case, the drive was probably long enough to warm up the battery, making the difference less significant overall.

ok I'm kinda understanding but I think it's still weird since it's I thought it was the calculated stats of the start and finish of that one particular drive based on a formula

take my last 2 drives
![image](https://user-images.githubusercontent.com/54423181/73225759-c3ad1e80-413b-11ea-8a78-487a27a58543.png)
58 min drive I had some limited regen. 
45 min drive I gained full regen ~15 minutes into the drive. but both show nothing because the snowflake probably means it's not accurate? the car shows a 234wh/mi for the last drive which is about 100% efficient, which teslamate would show normally

**Comment by bpankz** [comment] 2020-01-28 01:02
> I have a question about the drives dashboard.
> Might be the wrong thread to ask for, but for me it sounds at least not 100% wrong to ask here.
> 
> In the previous versions < 1.15.x on the drives dashboard there where the start and end odometer values visible, which was grate for the use as driver's logbook to bill the milage allowance to the company I am working for. Is there an easy way to show these values again or to introduce a new dashboard (i.e. driver's logbook) for this issue?

the data is still in the database under start_km and end_km I believe so it could be added back or to a new dashboard. I could probably help out once I learn how to in grafana

**Comment by Delta-99** [comment] 2020-01-28 02:26
Yeah, I'm missing all the data that has been removed from the Drives dashboard. It almost seems useless now!!

1. I think there was another column for distance beside the actual km driven.
2. Start and end odometer reading like has been pointed out.
3. And the efficiency numbers. I see some of the discussion above and don't have time to understand the details etc. But I would like those numbers to be shown again. Then the user can decide whether they are useless or not. With the added snowflake it will give the user an indication whether it is inaccurate. Other calculations can still ignore this data if needed.

Maybe it would be better to add the "old" Drives dashboard back in and call it Drives (legacy) or something.

How easy is Grafana to work with in order to create it ourselves?

**Comment by bpankz** [comment] 2020-01-28 03:00
Try renaming this to .json and import it. I added "Odo Start" and "Odo End" to the most up to date Drives dashboard. Seems pretty easy to add in stuff. Add in the sql, add in the column name, add in the visualization.
[Drives w_Odometer.json.txt](https://github.com/adriankumpf/teslamate/files/4120446/Drives.w_Odometer.json.txt)

**Comment by bpankz** [comment] 2020-01-28 15:59
As a quick thing for people who want to see the numbers, if you go into the Drives dashboard, click on the Drive header under the car name, hit Edit, 
look for

`    duration_min > 1 AND distance > 1 AND ( 
      start_position.usable_battery_level IS NULL OR
      -- ((start_position.battery_level - start_position.usable_battery_level) = (end_position.battery_level - end_position.usable_battery_level)) OR
      (end_position.battery_level - end_position.usable_battery_level) = 0 
    ) as is_sufficiently_precise,`

change to

`    duration_min > 1 AND distance > 1 as is_sufficiently_precise,`

hit Query inspector to make sure there aren't any errors then hit save at the top. and you should see all the numbers

**Comment by bruendi** [comment] 2020-01-28 18:47
> Try renaming this to .json and import it. I added "Odo Start" and "Odo End" to the most up to date Drives dashboard. Seems pretty easy to add in stuff. Add in the sql, add in the column name, add in the visualization.
> [Drives w_Odometer.json.txt](https://github.com/adriankumpf/teslamate/files/4120446/Drives.w_Odometer.json.txt)

Thank you very much! Exactly what I want to achieve.

**Comment by adriankumpf** [comment] 2020-02-04 16:48
I am more than willing to discuss the definition of when the values can be considered precise enough. The [current definition ](https://github.com/adriankumpf/teslamate/issues/390#issuecomment-579319123)is certainly somewhat arbitrary and can be further improved (PRs are always welcome). 

However, I don't think it makes sense to display consumption values that are demonstrably and knowingly incorrect. If you disagree, there is always the possibility to modify the existing dashboards. 

Since code snippets have already been posted, I consider this solved and close it for now.

**Closed by adriankumpf** 2020-02-04 16:48 UTC
Labels: bug

**Comment by muffstic** [comment] 2021-04-09 16:48
> Try renaming this to .json and import it. I added "Odo Start" and "Odo End" to the most up to date Drives dashboard. Seems pretty easy to add in stuff. Add in the sql, add in the column name, add in the visualization.
> [Drives w_Odometer.json.txt](https://github.com/adriankumpf/teslamate/files/4120446/Drives.w_Odometer.json.txt)

Can you explain how to import this? I'm having the same issue with kwh and consumption being blank for every drive.

**Comment by bpankz** [comment] 2021-04-09 18:10
> Can you explain how to import this? I'm having the same issue with kwh and consumption being blank for every drive.

Fixed since convert_km changed and it didn't show any data.
[Drives w_Odometer.json.txt](https://github.com/adriankumpf/teslamate/files/6287637/Drives.w_Odometer.json.txt)

if you only want to change the regular drives dashboard to show efficiency all the time, remove
`CASE WHEN is_sufficiently_precise THEN `
from the queries like below

**find**
`    CASE WHEN is_sufficiently_precise THEN range_diff * car_efficiency / distance * 1000 * CASE WHEN '$length_unit' = 'km' THEN 1
                                                                                                WHEN '$length_unit' = 'mi' THEN 1.60934
                                                                                           END`
**change to**
`    range_diff * car_efficiency / distance * 1000 * CASE WHEN '$length_unit' = 'km' THEN 1
                                                         WHEN '$length_unit' = 'mi' THEN 1.60934`

**find**
`    CASE WHEN is_sufficiently_precise THEN distance / range_diff
         ELSE NULL
    END AS efficiency`
**change to**
`    distance / range_diff AS efficiency`
