### ISSUE TITLE
New Grafana Chart - Monthly Stats

### ISSUE THREAD

**Issue by pratik5705** [adriankumpf/teslamate#664] opened 2020-04-29 18:47 UTC
**Is your feature request related to a problem? Please describe.**
I was trying to figure out my estimated miles driven per month and how that has changed with COVID.

Would it be possible to add some monthly stats to the grafana chart, broken down by calendar month:
Miles Driven
Charges
Charging Cost
Fuel Efficiency

I am sure there are others. 

Love this project, amazing work. Keep up the great work.

**Comment by cwanja** [comment] 2020-04-30 03:08
Tried using the Trip dashboard and setting the time to 30 (or 31) days. Should include every thing you are after.

**Comment by pratik5705** [comment] 2020-04-30 13:24
Thanks for the tip! Yes, it is. However, I was looking for something that
is comparative - compare April to March, etc. Would that have too many
variations?

Pratik

**Comment by Dulanic** [comment] 2020-04-30 17:02
So I began working on it... but I dont like the layout yet.....

![image](https://user-images.githubusercontent.com/2948206/80738339-7c3b8300-8ada-11ea-992d-7e0fa5f7660b.png)

**Comment by cwanja** [comment] 2020-04-30 17:30
Not the _best_ solution, but could you just open two tabs or windows and compare it? Are you really hitting this dashboard daily or weekly, or just once a month? If the latter, opening two tabs or windows seems like the best solution (in my opinion). Not saying you could not get some dashboard to eventually do it. Just wonder if it is worth the effort.

**Comment by pratik5705** [comment] 2020-04-30 18:54
So I started with the Trips dashboard and removed some of the panels and duplicated the first panel (total distance). Using time shift property of the panel, I was able to get last 30 days and last 60-30days to show up.

First screenshot showing the 2 different values (time range set to last 30 days):
![image](https://user-images.githubusercontent.com/4359069/80747913-2377e480-8af2-11ea-927a-88831053badd.png)

Second screenshot confirming the right value shows up (time range set to now-60d & now-30d). However, the bottom panel also shows the same calculation.
![image](https://user-images.githubusercontent.com/4359069/80747717-dbf15880-8af1-11ea-99ce-27f801689fa6.png)

Screenshot showing the change to the relative time/time shift settings.

I am going to duplicate all the panels on the top to the bottom and potentially a third time to show
last 30 days
last 60-30 days
last 90-60 days

If I save this dashboard as a copy, will it get overwritten on the next update (i.e., when I update all the containers for the next version of TeslaMate?)
Thanks.

**Comment by pratik5705** [comment] 2020-04-30 19:02
Ok, here is the copy with 2 sections showing last 30 days and last 60-30 days. Figured out the have to leave relative time blank and time shift 30d in the second set. Set the time filter to last 30 days and this works correctly.

![image](https://user-images.githubusercontent.com/4359069/80748892-a3eb1500-8af3-11ea-8888-adb65f349e59.png)

**Comment by pratik5705** [comment] 2020-04-30 19:31
Ok, it is complete.

![image](https://user-images.githubusercontent.com/4359069/80751205-64bec300-8af7-11ea-8357-e408c9c805d7.png)

I am posting the JSON file (zipped) if anyone is interested in making this. 
[TripCopy.zip](https://github.com/adriankumpf/teslamate/files/4560794/TripCopy.zip)

Thanks community for showing me the way to do it!

**Comment by DrMichael** [comment] 2020-05-01 12:41
Hmm, I thought, you meant more something like this?
![Trip-Monatsstatistik](https://user-images.githubusercontent.com/8087682/80806027-d5c6af00-8bb9-11ea-8843-988a74c809cd.png)

Could we learn from Teslalogger? :-)

**Comment by pratik5705** [comment] 2020-05-01 12:56
That is what I was initially thinking but cwanja's tip to use the trip
dashboard, led me down a different path. Can you share the json for the
dashboard? I would like to see the query.

Pratik

**Comment by DrMichael** [comment] 2020-05-01 13:14
Sure: https://github.com/bassmaster187/TeslaLogger/blob/master/TeslaLogger/Grafana/Trip%20Monatsstatistik.json

The query is:
SELECT DATE_FORMAT(StartDate, '%Y / %m') as date, \nsum(DurationMinutes)/60 as sum_duration_h, \nsum(km_diff) as sum_km,\nsum(consumption_kWh) as sum_consumption_kwh, \nsum(consumption_kWh) / sum(km_diff) * 100 as avg_consumption_kwh,\navg(outside_temp_avg) as avg_outside_temp,\ncount(*) as cnt\nfrom trip WHERE \n  $__timeFilter(StartDate) and km_diff < 1000 \n  group by DATE_FORMAT(StartDate, '%Y-%m')\n

**Comment by pratik5705** [comment] 2020-05-01 18:16
I am working on converting this to work with Teslamate. Have the base
working, need to do the unit conversion. The consumption values are not in
the drives table, will look at the drive chart to calculate these values.

Will submit the completed dashboard once done.

Thanks,
Pratik

**Comment by pratik5705** [comment] 2020-05-01 21:56
Here is the ported over dashboard from the above linked TeslaLogger dashboard. I didn't do the kWh/100 mi calculation. I can work on it, if you are interested in including this to TeslaMate. Also, some formatting might need to be checked on for km units.
Thanks again for sharing a path forward.
[Trip Stats Copy-1588370071040.zip](https://github.com/adriankumpf/teslamate/files/4566423/Trip.Stats.Copy-1588370071040.zip)

**Comment by DrMichael** [comment] 2020-05-31 13:23
I also worked a bit on this... Please comment. And please check C/F and km/mi...

(I am not happy yet with the units of the "Distance driven".)

[Monthly Statistics-1590931103243.zip](https://github.com/adriankumpf/teslamate/files/4707697/Monthly.Statistics-1590931103243.zip)

**Comment by DrMichael** [comment] 2020-06-02 11:13
I would like to put links behind the "Distance driven" and "Energy charged" fields to jump to "Drives" and "Charges" respectively for the given month. Can anybody help me to get the time interval in the link?

It should be something like `from=${__cell_0}&to=${__cell_0}+1m`, (cell 0 holding the milliseconds since epoch), but the "+1m" does not work...

Any ideas?

**Comment by DrMichael** [comment] 2020-06-04 09:36
Ok, I got further. Any comments? Is it useful anyway? :-)

![2020-06-04 11_34_06-Microsoft Edge](https://user-images.githubusercontent.com/8087682/83740663-73991800-a657-11ea-9358-3b3c84da3086.png)

[Monthly _ yearly statistics for drives and charges-1591263329309.zip](https://github.com/adriankumpf/teslamate/files/4729007/Monthly._.yearly.statistics.for.drives.and.charges-1591263329309.zip)

**Comment by Dulanic** [comment] 2020-06-04 13:38
Looks good, just needs a few updates. 

Very few languages use Ø . Not sure if I would hard code that. 

Also, my isn't formatted.... Oh I see, you added mi, but you set it for sum_distance_km, need to update to sum_distance_mi.

**Comment by DrMichael** [comment] 2020-06-04 16:25
> Very few languages use Ø . Not sure if I would hard code that.
Took that out...

> Also, my isn't formatted.... Oh I see, you added mi, but you set it for sum_distance_km, need to update to sum_distance_mi.
Rigth.

> I wonder if we should consider averaging the "Efficiency", quoted since that's still up for discussion as to the right wording for that. At least the avg of it.
I am not sure about that either. But, it is about **energy** added... I used _charge_energy_used_, not sure, whether that is the right one. I had also to take out charges with charge_energy_used==0. (That I get, when the battery is full. Then once in a while it will add 0.1-0.2 kWh (charge_energy_added), but charge_energy_used is zero.)

**Comment by DrMichael** [comment] 2020-06-04 16:26
New version

[Monthly _ yearly statistics for drives and charges-1591287586179.zip](https://github.com/adriankumpf/teslamate/files/4731400/Monthly._.yearly.statistics.for.drives.and.charges-1591287586179.zip)

![2020-06-04 18_25_35-FritzBoxTraffic](https://user-images.githubusercontent.com/8087682/83784886-e377c480-a690-11ea-821b-f0e43e980e4d.png)

**Comment by natrlhy** [comment] 2020-06-04 19:07
Coming along! I just imported this dashboard. I had 1000 free super charging miles I started to use up. These charges aren't showing up for me.

I had also opened up this [request](https://github.com/adriankumpf/teslamate/issues/724) that may tie along this one perhaps?

**Comment by DrMichael** [comment] 2020-06-05 09:21
> I had 1000 free super charging miles I started to use up. These charges aren't showing up for me.

What do you mean with that? Are not showing up where?!?!
Can you check it with this version and explain?

[Monthly _ yearly statistics for drives and charges-1591348853151.zip](https://github.com/adriankumpf/teslamate/files/4735111/Monthly._.yearly.statistics.for.drives.and.charges-1591348853151.zip)

**Comment by natrlhy** [comment] 2020-06-05 14:49
Here are my charges:
![image](https://user-images.githubusercontent.com/19696424/83888948-620b4b00-a6ff-11ea-825f-43b88a7f1115.png)

I was using your Monthly _ yearly statistics for drives and charges-1591277192096.zip version and here is what I see:

![image](https://user-images.githubusercontent.com/19696424/83890377-8ddb0080-a700-11ea-9105-56e6cf0ff10b.png)

My screenshot above seems to show that the super charges aren't showing up in the monthly/yearly stats dashboard and version mentioned above.

**Comment by DrMichael** [comment] 2020-06-05 15:26
@natrlhy Could we jump on discord? https://discord.com/channels/631168014540341268/631168014540341270

**Comment by DrMichael** [comment] 2020-06-05 15:27
@natrlhy What do you get with

`select start_date, end_date, charge_energy_added from charging_processes where start_date BETWEEN '2020-05-01T00:00:00.000Z' AND '2020-06-01T00:00:00.000Z';`

**Comment by DrMichael** [comment] 2020-06-05 16:02
Anyway, new version...

[Statistics-1591372901660.zip](https://github.com/adriankumpf/teslamate/files/4737239/Statistics-1591372901660.zip)

**Comment by Dulanic** [comment] 2020-06-05 16:38
For charge_energy, for vehicle usage you'd want charge_energy_added as that is the amount of power added to the batteries. If you want to see a "guess" as to how much energy was taken from the grid, thjat is charge_energy_used. I'd recommend just using charge_energy_added .

So this was my idea /w efficiency....

https://pastebin.com/Wx0ENLdz

**Comment by DrMichael** [comment] 2020-06-05 17:09
Well, I'd like to get energy taken from the grid... That is, what I have consumed.

Efficiency is interesting, but a bit academic IMHO. And we have an Efficiency dashboard already.

But, do you have an idea, how to deal with the timezones? It appears, that they are stored in UTC. But, when displayed in Grafana, they are in local time. And I would like to have the month started at the first day 00:00 local time, not UTC time...

**Comment by DrMichael** [comment] 2020-06-06 09:34
> So this was my idea /w efficiency....

@Dulanic I never looked into that efficiency thing, what exactly does it tell me? And what do the colors tell? Why did you color the Distance driven?

Do you perhaps have a solution for the UTC/local timezone issue? All dates showed in Grafana are essentially in UTC, meaning for UTC-7 the e.g. month starts on the evening of the last day of the previous month... Not good.

**Comment by DrMichael** [comment] 2020-06-07 13:47
Well, this is as close as I can get with the timezone issue: the dashboard displays in UTC. But for that it should provide reasonable data.

[Statistics-1591537570944.zip](https://github.com/adriankumpf/teslamate/files/4742168/Statistics-1591537570944.zip)

**Comment by Dulanic** [comment] 2020-06-07 15:10
Databases and timezones get to be fun :) So grafana will convert the timezone if it can, to make this possible, I recommend using epoch. 

As to why I colored the distance... mistake.

EX: for date field so it can convert can be done like so: extract(epoch from date_trunc('$period', start_date)) * 1000

Other options are to convert the timezone see below for examples:

SELECT date, timezone('UTC',date) , date AT TIME ZONE current_setting('TIMEZONE'), timezone('UTC',date) AT TIME ZONE current_setting('TIMEZONE')
from charges

**Comment by DrMichael** [comment] 2020-06-07 15:26
> As to why I colored the distance... mistake.

:-) I like the color...

> EX: for date field so it can convert can be done like so: extract(epoch from date_trunc('$period', start_date)) * 1000

The problem is to adjust epoch for local timezone also in retrospect. So, I am in +2 currently and +1 in winter. I don't see a feasible solution...

> SELECT date, timezone('UTC',date) , date AT TIME ZONE current_setting('TIMEZONE'), timezone('UTC',date) AT TIME ZONE current_setting('TIMEZONE') from charges

Gives all the same. Well, the containers (postgres and grafana) are running with UTC and the postgres timezone is also UTC. Grafana concerts it then to local time, when that is set in the settings.

**Comment by Dulanic** [comment] 2020-06-07 15:59
Ah yeah no I run my container in my timezones 😁

**Comment by Dulanic** [comment] 2020-06-07 21:42
As a follow up, we could recommend people set their timezone /w the containers if we wanted that functionality. It's a easy flag....  EX: 

`-e TZ=America/Chicago`

**Comment by DrMichael** [comment] 2020-06-08 08:35
https://stackoverflow.com/questions/44394295/how-to-change-timezone-of-postgresql-9-5-on-docker talks about setting TZ and PGTZ in the docker-compose.yml.

I tried, but was not successful.

@adriankumpf Any specific reason, why all containers except teslamate run in UTC?

**Comment by DrMichael** [comment] 2020-06-10 09:29
Ok, I am running the database container and postgres now in local timezone.

Now, the following should do the job:
`date_trunc('month', TIMESTAMP WITH TIME ZONE start_date, current_setting('TIMEZONE')) as date`
(It does with '2001-02-16 20:38:40-05'...)

But I get `pq: syntax error at or near "start_date"`. What is wrong here?!?

**Comment by DrMichael** [comment] 2020-06-11 09:15
So strange, I have not the faintest, where that "Etc/UTC" is still coming from. Simplified in Grafana it looks like:
![2020-06-11 11_11_39-Window](https://user-images.githubusercontent.com/8087682/84367554-b0738a80-abd4-11ea-90b2-84da5d243b84.png)
In psql it looks like:
![2020-06-11 11_12_04-Window](https://user-images.githubusercontent.com/8087682/84367577-b9fcf280-abd4-11ea-897a-2dd8a91bb7d9.png)
And `date` in the container gives me `Thu 11 Jun 2020 11:12:56 AM CEST`

**Comment by DrMichael** [comment] 2020-06-11 10:28
Ok, it turned out, that although PGTZ is set to 'Europe/Berlin', /var/lib/postgresql/data/postgresql.conf contains 'Etc/UTC'. Changing that to 'Europe/Berlin' appears to fix the situation.

**Comment by Dulanic** [comment] 2020-06-11 12:28
Oh that's easy, DST.

**Comment by DrMichael** [comment] 2020-06-11 12:32
Hmmm, what do you mean?

**Comment by Dulanic** [comment] 2020-06-11 13:00
Daylight savings start and end.

**Comment by DrMichael** [comment] 2020-06-11 13:17
Yes, sure. But my question was more: why do I get Etc/UTC in Grafana and Europe/Berlin in psql: Because PGTZ sets the timezone for the **clients**.

**Comment by Dulanic** [comment] 2020-06-11 13:28
Grafana must be doing it, just don't know why.

**Comment by DrMichael** [comment] 2020-06-11 13:32
Ah, no.
The issue is (was), that PGTZ sets the timezone for psql. But it is not set, when Grafana issues the query. So, after setting the timezone to Europe/Berlin in postgresql.config, also Grafana shows and uses that timezone. (I hope, that does not break anything else... :-)

**Comment by DrMichael** [comment] 2020-06-12 08:13
Ok, I share my latest version. Remember: you must change the timezone in the database container in `/var/lib/postgresql/data/postgresql.conf` to your local timezone!

(If you do not, it works with UTC, which leads to misleading entries in "Period")

@adriankumpf Could we take care for that in the distributed container? Or simpler approach: just store the local timezone in the settings... Or set the timezone of the database to the local one?

[Statistics-1591949142513.zip](https://github.com/adriankumpf/teslamate/files/4769549/Statistics-1591949142513.zip)

**Comment by DrMichael** [comment] 2020-10-01 12:36
Committed my latest version. Still the timezone issue exists... The periods start at the time, your postgres is running under, standard is Etc/UTC. https://github.com/adriankumpf/teslamate/pull/958

**Closed** 2020-12-08 18:49 UTC
Labels: idea
