### ISSUE TITLE
Does not detect restart of charging session while 'trying to sleep'

### ISSUE THREAD

**Issue by pkuehnel** [adriankumpf/teslamate#1397] opened 2021-02-25 13:02 UTC
**Describe the bug**
Using Streaming-API: When car stops charging due to reaching chargelimit, after a few minutes/seconds (i don't know exactly) TeslaMate shows car is trying to sleep for XX. When I now open the app (car not sleeping) and set the chargelimit to a higher SOC and the car starts charging again TeslaMate does not detect the charge start.

**Expected behavior**
Tesla Mate should change state from 'trying to sleep' to 'charging'

**How to reproduce it (as minimally and precisely as possible)**:
1. Use Streaming-API
2. Plug in the car and let it charge
3. Reduce charge limit so car stops charging due to higher SOC than charge limit
4. Wait until TeslaMate shows 'Trying to sleep'
5. Increase the charge limit via Tesla App to a higher SOC than current SOC
6. Car starts charging but TeslaMate still shows 'trying to sleep'

**Environment**

- TeslaMate version: 1.21.5
- Type of installation: Docker

**Comment by pkuehnel** [comment] 2021-03-02 09:12
Same issue when you park the car, wait until TeslaMate UI shows 'trying to sleep' and then plug in the car. Start of charging session is not detected.

**Comment by adriankumpf** [comment] 2021-03-02 16:56
Related to / duplicate of #1274. The car can only fall asleep if no queries are made via the API. TelsaMate can only detect (re)started charging via the Streaming API. But this requires that the API actually returns any data at that point in time which sometimes may not be the case for reasons beyond TeslaMate's control.

**Closed by adriankumpf** 2021-03-02 16:56 UTC
