### ISSUE TITLE
Tesla API timeout error 504 flooding CLI

### ISSUE THREAD

**Issue by tobiasehlert** [adriankumpf/teslamate#506] opened 2020-03-10 19:50 UTC
**Describe the bug**

There are a lot of errors showing up in the CLI when showing the TeslaMate docker logs..

**To Reproduce**

1. Go to server CLI
2. Change to TeslaMate directory
3. run `docker-compose logs -f` to view logs

**Expected behavior**

No errors shown or maybe more details of the actual error that is recorded.

**Relevant entries from the logs**

```
teslamate_1  | 19:00:02.997 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:00:02.997 car_id=1 [error] Error / :timeout
teslamate_1  | 19:00:59.722 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:00:59.723 car_id=1 [error] Error / :timeout
teslamate_1  | 19:01:58.698 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:01:58.698 car_id=1 [error] Error / :timeout
teslamate_1  | 19:08:13.525 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:08:13.525 car_id=1 [error] Error / :timeout
teslamate_1  | 19:09:10.536 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:09:10.536 car_id=1 [error] Error / :timeout
teslamate_1  | 19:12:44.590 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 19:12:44.590 car_id=1 [error] Error / :timeout
```

**Operating environment**

- TeslaMate Version: v1.17.1
- Advanced Docker Setup with Traefik
- OS: CentOS 7

**Comment by adriankumpf** [comment] 2020-03-11 14:52
Duplicate of #504

> **Expected behavior**
>
> No errors shown or maybe more details of the actual error that is recorded.

I don't think it's a good idea to hide those errors. It is important to know when the Tesla servers are unreliable. All available information is already displayed.

**Closed by adriankumpf** 2020-03-11 14:52 UTC
