### ISSUE TITLE
Phases were not shown correctly in charge detail screen

### ISSUE THREAD

**Issue by mailkluge** [adriankumpf/teslamate#2406] opened 2022-01-29 20:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In Charge Details a wrong number of used phases is shown. In my case, three phases were used. Two phases are shown.

### Relevant log output

```shell
I added a screenshot to show an example.
```

### Screenshots

![image](https://user-images.githubusercontent.com/57233414/151676831-77e6c847-ad28-4e66-ab16-18729131f6fb.png)

### Type of installation

Docker

### Version

v1.25.2

**Comment by adriankumpf** [comment] 2022-01-29 22:28
Duplicate of https://github.com/adriankumpf/teslamate/issues/414

**Closed by adriankumpf** 2022-01-29 22:28 UTC
