### ISSUE TITLE
IP:4000 ERR_CONNECTION_REFUSED after latest update to v1.25.2

### ISSUE THREAD

**Issue by Tgerstb** [adriankumpf/teslamate#2315] opened 2022-01-14 11:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Teslamate refuses connection in all so far tested browsers (Edge, Chrome, Firefox) on different devices (PC and mobile) using IP:4000 after latest update to v 1.25.1.
IP is pingable and PUTTY connection to RPi works. RPi rebooted after docker-compose pull
docker-compose.yml changed to the newest mosquitto setting
Grafana works under IP:3000, admin login done as described and PW changed.
Latest Drives and Charges are NOT visible in Grafana after update.
docker-compouse up -d all builds are up to date
docker run hello world works

### Expected Behavior

as used to with v.1.24.2

### Relevant log output

```shell
Retrieval failed:
docker-compose logs teslamate
Attaching to pi_teslamate_1
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted
```

### Type of installation

Docker

### Version

v1.25.2

**Comment by dranreb38** [comment] 2022-01-14 14:52
RPI 4 buster ?

**Comment by isjupr** [comment] 2022-01-14 14:59
Same problem here.

**Comment by adriankumpf** [comment] 2022-01-14 15:30
Duplicate of #2302

**Closed by adriankumpf** 2022-01-14 15:30 UTC
