### ISSUE TITLE
Streaming API causes Tesla app to report position incorrectly

### ISSUE THREAD

**Issue by Sharkku** [adriankumpf/teslamate#1232] opened 2021-01-21 15:00 UTC
When TeslaMate is connected via the streming API, the position of the car is reported incorrectly in the Tesla app. When selecting "Position" (or "Place"? - I don't know what word is used in the English version) within the app, the position is briefly shown correctly for about a second, but as soon as it updates, it goes completely wonky, showing the car in the middle of Sahara, Pacific Ocean, or something like that, moving several rhousand miles for each second, back and forth.

This does not occur if connected via the old polling method.

My car is a 2014 Model S85, with an MCU1 that was replaced about a year ago.

**Comment by adriankumpf** [comment] 2021-01-22 08:54
This is not a bug in TeslaMate but has to be fixed by Tesla. The only option we have is to disable the usage of Streaming API (on the TeslaMate settings page), if you want to Tesla app to show the correct location.

**Closed by adriankumpf** 2021-01-22 08:54 UTC
