### ISSUE TITLE
Grafana v8 and TeslaMate dashboard issues

### ISSUE THREAD

**Issue by PR-UK** [adriankumpf/teslamate#1728] opened 2021-06-15 19:28 UTC
### Describe the bug:

Since updating to Grafana v8 I'm getting the following error on some of the Teslamate dashboards:

`convert frame from rows error: sql: Scan error on column index 6, name "usable SOC [%]": converting NULL to int16 is unsupported`

### Expected behaviour

Data to load correctly on the dashboards

### Screenshots
![Screenshot 2021-06-15 at 20 24 42](https://user-images.githubusercontent.com/65460246/122111493-ba4b5180-ce17-11eb-8520-d387c6fec635.png)

![Screenshot 2021-06-15 at 20 25 14](https://user-images.githubusercontent.com/65460246/122111568-cd5e2180-ce17-11eb-99e4-b451b7918c80.png)

### Environment
TeslaMate version: 1.23.3
Grafana version: 8.0.2
Type of installation: Docker
OS TeslaMate is installed on: unRAID 6.9.2
User OS & Browser: Edge / Safari

Hopefully this information is useful as I don't usually submit things on GitHub. Thanks.

**Comment by adriankumpf** [comment] 2021-06-15 20:23
Duplicate of https://github.com/adriankumpf/teslamate/issues/1723. we don't support Grafana 8 yet.

**Comment by PR-UK** [comment] 2021-06-15 20:56
Thanks, I've rolled the docker back to Grafana 7.5.8 and all back to working.

**Comment by jherby2k** [comment] 2021-06-25 13:58
Its not super apparent (at least to me) that you require Grafana < 8. Might want to put this in your "requirements" page in the docs.

**Closed** 2022-01-21 17:31 UTC
Labels: area:grafana, area:dashboard

**Comment by brianmay** [comment] 2022-03-11 01:58
Confirmed it now works for Grafana >= 8.3.4
