### ISSUE TITLE
Updates Dashboard # of charges

### ISSUE THREAD

**Issue by KnightwhosayNi777** [adriankumpf/teslamate#1018] opened 2020-10-16 17:13 UTC
Directly after the update to 2020.40.4, 17 charges are displayed. Of course this is not true, how is this to be understood?

![IMG_0280](https://user-images.githubusercontent.com/65669081/96288272-6ae02780-0fe3-11eb-860b-73f45a65add3.jpeg)

**Comment by petariga** [comment] 2020-10-16 20:02
I have the same experience, my guess is that the value in "# of Charges" is shifted one row up.

Nevertheless, talking about the Updates dashboard, I would strongly suggest to change column "Since Last Update" to "Used for # of days" or something similar, which would just show the # of days the car has been on a particular version of software. In my opinion "Since last update" can be quite confusing, because it states a value, which is in fact connected to a version one row below, not the one it is in. The value in weeks can be confusing sometimes as well, because when you compare two rows which both state 3 weeks - it could be 15 days in one case and 6 more in the other (I am not sure about the exact values, but surely thay can be 6 days from each other and state the same # of weeks).

**Comment by KnightwhosayNi777** [comment] 2020-10-16 22:41
It is correct, the installed TM version is 1.20

For my understanding the idea behind this column is to see if and which impact the Tesla software version has on the range.

**Comment by petariga** [comment] 2020-10-17 12:56
AFAIK the average range value and # of charges have been just added in the TM version 1.20.0. Previously the Update dashboard was used to show how long the car was sitting an a particular version of firmware or how often the car receives firmware updates.

**Comment by dyxyl** [comment] 2020-10-19 11:21
I was confused by **"Since Last Update"** too.  **"Since Previous Upgrade"** would better.

**Comment by petariga** [comment] 2020-10-19 11:37
I my opinion better structure of the table with the time value in a row with connected firmware version would be better than only renaming the column. If we rename just the column, we will keep the unnatural one row shift of corresponding data (connected firmware version).

**Comment by petariga** [comment] 2020-10-23 17:24
After another upgrade to 2020.40.8 I can clearly state, that the values in the column **# of Charges** are just incorrectly shifted one row up. I assume that the same is true for the last column **Avg rated range**.

**Comment by adriankumpf** [comment] 2020-10-24 10:45
Duplicate of #991

**Closed by adriankumpf** 2020-10-24 10:45 UTC
