### ISSUE TITLE
Have MQTT respect the units set in the dashboard

### ISSUE THREAD

**Issue by djuniah** [adriankumpf/teslamate#927] opened 2020-09-18 20:39 UTC
**What would you like to be added**:  Currently distance units are hard-coded into topics like "teslamate/cars/1/ideal_battery_range_km".  It would be nice to have a more generic topic like "teslamate/cars/1/ideal_battery_range" that just used the units set in the dashboard.  Alternatively, a second topic like "teslamate/cars/1/ideal_battery_range_mi" would be nice to have.

**Why is this needed**:  I use the MQTT functionality to get data into Home Assistant and it seems like the only option is to use km at the moment (at least according to what i see in the docs)

**Additional context**:

**Comment by adriankumpf** [comment] 2020-09-24 09:46
Duplicate of https://github.com/adriankumpf/teslamate/issues/230

**Closed by adriankumpf** 2020-09-24 09:46 UTC
Labels: request
