### ISSUE TITLE
Maintenance reminders

### ISSUE THREAD

**Issue by Nakatomi2010** [adriankumpf/teslamate#799] opened 2020-06-19 19:44 UTC
**What would you like to be added**:
I'd like to see a section where in we can log maintenance which has been done to the vehicle.  Maybe even allow for maintenance reminders, like "Hey, it's been 10,000 miles, maybe get your tires rotated?" and such.

**Why is this needed**:
I'm getting old and forgetful.  Since I don't take it in for regular oil changes, I start to forget when the maintenance was last done, or needed.

**Additional context**:
None really.  Every vehicle needs maintenance of some kind.  With as much data as this thing can collect, I don't see why we can't have it start making actionable notifications out of it.

**Comment by cwanja** [comment] 2020-06-22 19:35
#245 😊

**Comment by Nakatomi2010** [comment] 2020-06-22 20:10
Nuts.  Sorry about that

**Comment by adriankumpf** [comment] 2020-06-25 12:07
Yup, that's a duplicate of #245  👍

**Closed by adriankumpf** 2020-06-25 12:07 UTC
Labels: request
