### ISSUE TITLE
v1.27.1 Blue dot for location disappeared

### ISSUE THREAD

**Issue by LiamWangjy** [adriankumpf/teslamate#2935] opened 2022-10-08 08:08 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

In the previous versions of drive details, there was a blue dot showing where the car was when I moving the cursor on the trips. Now in v1.27.1, when I move the cursor, there is no blue dot showing where the car was, so I couldn't now the exact location on the map. Please help me with that, thank you.

### Expected Behavior

To show the exact location on the map when I moving the cursor, just like the previous versions.

### Steps To Reproduce

1. Select a trip in "Drives"
2. Click to open the tab which showing "Drive Details"
3. moving the cursor through left to right on the "Drive" tab (which shows the speed, power, range, SOC, etc.)
4. On the map tab, there is no blue dot showing where was my tesla.

### Relevant log output

```shell
teslamate_1  | 2022-10-08 01:10:43.276 [info] Refreshing access token ...
teslamate_1  | 2022-10-08 01:10:43.380 [info] POST https://auth.tesla.cn/oauth2/v3/token -> 200 (102.986 ms)
teslamate_1  | 2022-10-08 01:10:43.490 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-10-08 03:08:02.405 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-08 03:08:02.696 car_id=1 [info] Connecting ...
teslamate_1  | 2022-10-08 03:08:53.259 car_id=1 [info] Charging detected: -1 kW
teslamate_1  | 2022-10-08 03:13:12.801 car_id=1 [info] Charging detected: -1 kW
teslamate_1  | 2022-10-08 03:13:24.286 car_id=1 [info] Charging detected: -1 kW
teslamate_1  | 2022-10-08 03:14:47.980 car_id=1 [info] Charging detected: -1 kW
teslamate_1  | 2022-10-08 03:15:31.484 [info] Start of drive initiated by: %TeslaApi.Stream.Data{elevation: 2, est_heading: 76, est_lat: 31.190107, est_lng: 121.433311, est_range: 127, heading: 76, odometer: 29862.3, power: 3, range: 180, shift_state: "D", soc: 80, speed: 0, time: ~U[2022-10-08 03:15:31.408Z]}
teslamate_1  | 2022-10-08 03:15:31.484 car_id=1 [info] Driving / Start
teslamate_1  | 2022-10-08 03:30:17.743 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (908.853 ms)
teslamate_1  | 2022-10-08 03:30:18.248 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (502.850 ms)
teslamate_1  | 2022-10-08 03:30:18.558 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1665199809, heading: 258, latitude: 31.197786, longitude: 121.418596, native_latitude: 31.195924, native_location_supported: 1, native_longitude: 121.423232, native_type: "gcj", power: 1, shift_state: "P", speed: 0, timestamp: 1665199810742}
teslamate_1  | 2022-10-08 03:30:18.558 car_id=1 [info] Driving / Ended / 4 km – 15 min
teslamate_1  | 2022-10-08 03:30:18.558 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-08 03:34:36.709 car_id=1 [info] Suspending logging
teslamate_1  | 2022-10-08 04:04:37.266 car_id=1 [info] Vehicle is still online. Falling asleep for: 33 min
teslamate_1  | 2022-10-08 04:19:54.377 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-10-08 04:19:54.617 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-10-08 04:19:54.791 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-10-08 06:01:06.372 car_id=1 [info] Start / :online
teslamate_1  | 2022-10-08 06:01:06.694 car_id=1 [info] Connecting ...
teslamate_1  | 2022-10-08 06:04:08.748 car_id=1 [info] Suspending logging
teslamate_1  | 2022-10-08 06:14:38.835 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2022-10-08 06:14:39.130 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-10-08 06:14:39.194 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-10-08 07:10:43.491 [info] Refreshing access token ...
teslamate_1  | 2022-10-08 07:10:43.577 [info] POST https://auth.tesla.cn/oauth2/v3/token -> 200 (84.869 ms)
teslamate_1  | 2022-10-08 07:10:43.663 [info] Scheduling token refresh in 6 h
```

### Screenshots

![截屏2022-10-08 15 51 10](https://user-images.githubusercontent.com/83756175/194696663-c90ee53b-752c-431a-84d6-16783b2cb6bf.png)

### Type of installation

Docker

### Version

v 1.27.1

**Comment by cwanja** [comment] 2022-10-08 11:57
Duplicate of #2770

**Closed** 2022-10-18 05:04 UTC
