### ISSUE TITLE
Incorrect number of charge phases

### ISSUE THREAD

**Issue by tonypilborg** [adriankumpf/teslamate#670] opened 2020-05-02 06:26 UTC
In charging details, all my charges at home (only placed I have charged since installing 6 weeks ago - due to Covid) show as:

230 Volts (correct)
16 Amps (correct)
2 phases (clearly wrong)
11 Kw (correct)

Do the math 230 * 16 * 2 = 7.360 w

It should be 230 * 16 * 3 = 11 Kw

![image](https://user-images.githubusercontent.com/62705022/80856956-a1510280-8c4e-11ea-81cb-faa648887705.png)

I assume the API gives at least Volts, amps and wattage - not sure if it reports phases or this is calculated?? 

- TeslaMate Version: all since 1.18

**Comment by adriankumpf** [comment] 2020-05-02 10:19
Duplicate of #605, #414

**Closed by adriankumpf** 2020-05-02 10:19 UTC
