### ISSUE TITLE
Drive Details bug. There is no point in map, follow the timeline.

### ISSUE THREAD

**Issue by ironjing** [adriankumpf/teslamate#2887] opened 2022-09-09 02:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the mouse moves over the timeline, there is no point in map. The old version is fine.
my docker images version. 
<img width="674" alt="image" src="https://user-images.githubusercontent.com/17465146/189261223-fc9532a1-05e1-445e-881c-27c5127129e6.png">

<img width="816" alt="image" src="https://user-images.githubusercontent.com/17465146/189260739-550bb91f-1d51-4f44-be6f-173ca6d2359c.png">

### Expected Behavior

the point can move in the map. thank you.

### Relevant log output

```shell
no log
```

### Type of installation

Docker

### Version

v1.27.1

**Comment by cwanja** [comment] 2022-09-09 02:49
Duplicate of #2770

**Comment by ironjing** [comment] 2022-09-09 02:55
thank you. i got it

**Comment by ironjing** [comment] 2022-09-09 02:56
> Duplicate of #2770

thank you. i got it

**Closed** 2023-01-13 11:15 UTC
