### ISSUE TITLE
TeslaMate divides each drive into little bits

### ISSUE THREAD

**Issue by rybber78** [adriankumpf/teslamate#1062] opened 2020-10-31 14:20 UTC
**Describe the bug**

Each of my drives are being recorded, but divided up into little tiny bits, which makes it count each bit as an individual drive in itself.

**Expected behavior**

Every drive should be listed as one combined.

Going on a drive.

**Relevant entries from the logs**

I see some MFA exceptions in the log. Could this be connected to adding 2FA to my Tesla account??

```
paste logs here
```
    Args: [#Function<3.4852099/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [display_name: "KITT"]]

14:19:50.932 [error] Task #PID<0.5083.0> started from #PID<0.5072.0> terminating

** (stop) exited in: GenServer.call(TeslaMate.Mqtt.Publisher, {:publish, "teslamate/cars/1/update_available", "false", [retain: true, qos: 1]}, 10000)

    ** (EXIT) an exception was raised:

        ** (ErlangError) Erlang error: :timeout_value

            (tortoise 0.9.5) lib/tortoise/connection.ex:328: Tortoise.Connection.connection/2

            (tortoise 0.9.5) lib/tortoise.ex:269: Tortoise.publish/4

            (teslamate 1.20.1) lib/teslamate/mqtt/publisher.ex:41: TeslaMate.Mqtt.Publisher.handle_call/3

            (stdlib 3.12.1) gen_server.erl:661: :gen_server.try_handle_call/4

            (stdlib 3.12.1) gen_server.erl:690: :gen_server.handle_msg/6

            (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

    (elixir 1.10.4) lib/gen_server.ex:1023: GenServer.call/3

    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2

    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5

    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

nction: &:erlang.apply/2

    Args: [#Function<3.4852099/1 in TeslaMate.Mqtt.PubSub.VehicleSubscriber.handle_info/2>, [update_available: false]]
**Screenshots**
![image](https://user-images.githubusercontent.com/41877177/97781489-0b118100-1b8c-11eb-81be-4e62e916cad0.png)

**Data**

**Environment**

- TeslaMate version:
- Type of installation: Docker or Manual
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:

**Comment by adriankumpf** [comment] 2020-11-05 10:29
Duplicate of #1063

**Closed by adriankumpf** 2020-11-05 10:29 UTC
