### ISSUE TITLE
Vampire drain not calculated correctly in conjunction with Pre-heating

### ISSUE THREAD

**Issue by NeskireDK** [adriankumpf/teslamate#1419] opened 2021-03-08 10:51 UTC
Hi,

I having an issue with the calculation of vampire drain, and was hoping a kind soul could comment on my stats below.
I started pre-heating, when the car had 53%, as i know i parked the car at 55%, the loss should be 2% no?

![image](https://user-images.githubusercontent.com/10115530/110309720-fba2b880-8001-11eb-8fca-0fbfd86e0af8.png)

It seems that the vampire drain calculation, includes the %'s used for pre-heating as "vampire drain". See below.
![image](https://user-images.githubusercontent.com/10115530/110311749-871d4900-8004-11eb-9700-9ddadb54a7eb.png)

Teslamate reports 3% loss, by looks of it from these numbers: SOC 55% (usable 54%) - SOC (usable) 51%. Which is when i start driving. If i had kept pre-heating going for 40 minutes, wouldn't teslamate vampire loss be many % higher? 

I made a temp dump of my data, stripped naturally. 
https://aergraph.duckdns.org/dashboard/snapshot/kSGcqf2waCXH3YLesCBC1RDlsm4EZWpD
Preview here: 
![image](https://user-images.githubusercontent.com/10115530/110311539-36a5eb80-8004-11eb-981b-95de069869a4.png)

I'm experienced with sql, but i failed to find the underlying sql, other than this:

`SELECT
	$__time(date),
	convert_km(speed::numeric, '$length_unit') AS "Speed [$length_unit/h]",
	power AS "Power [kW]",
	convert_km([[preferred_range]]_battery_range_km, '$length_unit') AS "Range ($preferred_range) [$length_unit]",
	convert_km(est_battery_range_km, '$length_unit') AS "Range (est.) [$length_unit]",
	battery_level AS "SOC [%]",
	usable_battery_level AS "usable SOC [%]"
FROM
	positions
WHERE
 car_id = $car_id AND
 $__timeFilter(date)
ORDER BY
	date ASC`

**Comment by pkuehnel** [comment] 2021-03-11 10:15
Using Pre-Heating is calculated as vampire drain. In my opinion the Problem here is where does Vampire drain start and where does it stop? Is pre-heating vampire drain? Is sentry mode vampire drain? Is waking up the car via App Vampire drain? The car lost 5% while beeing online with sentry mode and preheating: Are the 5% due to preheating? due to sentry mode? due to just beeing online?

**Comment by adriankumpf** [comment] 2021-03-15 10:25
Duplicate of  #248

**Closed by adriankumpf** 2021-03-15 10:25 UTC
