### ISSUE TITLE
Korean currency unit

### ISSUE THREAD

**Issue by nanara1119** [adriankumpf/teslamate#1976] opened 2021-09-14 12:56 UTC
The Korea currency unit is WON (1 USD - 1200 WON )

There is a problem when input the total cost which is over 10,000 cannot save.

When tested, it was checked that the maximum input value was 9999.00.

I am wondering if there is any other solution.

**Comment by adriankumpf** [comment] 2021-09-19 13:07
Duplicate of https://github.com/adriankumpf/teslamate/issues/1064

**Closed by adriankumpf** 2021-09-19 13:07 UTC
