### ISSUE TITLE
MQTT topics for miles/farenheit

### ISSUE THREAD

**Issue by krelltunez** [adriankumpf/teslamate#954] opened 2020-09-28 22:09 UTC
Hi.  I'm new to Teslamate (and Home Assistant) but a long time TeslaFi and SmartThings user (who recently converted both!)...

**What would you like to be added**:  MQTT topics for US folks who use miles (for odometer, range, etc.) and Farenheit (inside and outside temps).

**Why is this needed**: There are settings to change this in Teslamate itself (and Grafana) but no ability to do it for MQTT (Home Assistant).

**Additional context**:  I know this can be done via templates in Home Assistant, and I intend to work on that, but it would be easier if there were topics available depending on user preferences.

That's it.  Hopefully this is something that could be worked in for a future release.

Thanks!!

**Comment by rhatguy** [comment] 2020-09-29 04:23
Converting the values into miles inside home assistant is fairly straightforward when you import the sensor into your configuration.yaml file

  - platform: mqtt
    name: tesla_estimated_range
    state_topic: "teslamate/cars/1/est_battery_range_km"
    unit_of_measurement: 'mi'
    value_template: >-
      {{ value|float/1.609 }}
    icon: mdi:map-marker-path

You can also then change your "unit system" from metric to imperial under "Configuration"->"General".  For me, this takes care of the celsius to fahrenheit conversion and my temperatures display in F.  Not arguing that it might be nice to have teslamate push these in native units..but at least its not hard to convert in home assistant.

**Comment by krelltunez** [comment] 2020-09-30 00:51
Yeah, that's exactly what I was setting up.  I still think it would be more artful if it included topics for km and mi.  Now I just need to get the system to do rounding, because I end up with like 12 decimal places in my range numbers!!!

As for temperature, I don't really understand how the sensors initially showed Celsius but then now show Farenheit - because I didn't change anything within Home Assistant.  But it's all good now - the sensors are correct!

**Comment by krelltunez** [comment] 2020-09-30 01:11
Got it - ended up using the following template:  {{ (value | float/1.609) | round(1) }}

**Comment by adriankumpf** [comment] 2020-10-03 11:11
Duplicate of #230.

**Closed by adriankumpf** 2020-10-03 11:11 UTC
Labels: request
